# Generated by tools/generate.jl; do not edit.
# Input SHA256: ebb8032d469a051dcee21389ea8461ad8f03b32900a9e94f426b4db64a5adc77
"""Convert(fx, fr, rho, x): source §4.9.1; exact kernel and final projection."""
Convert(fx, fr, rho, x) = P.scalar(P.identity, (fx,), fr, rho, (x,))
public Convert
"""ScaledConvert: singleton block semantics with one final projection."""
ScaledConvert(fs1, f1, fr, rho, s1, c1) = P.scaled(P.identity, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockConvert: positional elementwise semantics, retaining result scale s."""
BlockConvert(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.identity, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledConvert, BlockConvert

"""Abs(fx, fr, rho, x): source §4.10.1; exact kernel and final projection."""
Abs(fx, fr, rho, x) = P.scalar(P.magnitude, (fx,), fr, rho, (x,))
public Abs
"""ScaledAbs: singleton block semantics with one final projection."""
ScaledAbs(fs1, f1, fr, rho, s1, c1) = P.scaled(P.magnitude, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockAbs: positional elementwise semantics, retaining result scale s."""
BlockAbs(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.magnitude, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledAbs, BlockAbs

"""Negate(fx, fr, rho, x): source §4.10.1; exact kernel and final projection."""
Negate(fx, fr, rho, x) = P.scalar(P.negate, (fx,), fr, rho, (x,))
public Negate
"""ScaledNegate: singleton block semantics with one final projection."""
ScaledNegate(fs1, f1, fr, rho, s1, c1) = P.scaled(P.negate, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockNegate: positional elementwise semantics, retaining result scale s."""
BlockNegate(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.negate, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledNegate, BlockNegate

"""CopySign(fx, fy, fr, rho, x, y): source §4.10.2; exact kernel and final projection."""
CopySign(fx, fy, fr, rho, x, y) = P.scalar(P.copy_sign, (fx, fy), fr, rho, (x, y))
public CopySign
"""ScaledCopySign: singleton block semantics with one final projection."""
ScaledCopySign(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.copy_sign, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockCopySign: positional elementwise semantics, retaining result scale s."""
BlockCopySign(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) =
    P.block_apply(P.copy_sign, n, ((fs1, f1), (fs2, f2)), fs, fr, rho, ((s1, cs1), (s2, cs2)), s)
public ScaledCopySign, BlockCopySign

"""Add(fx, fy, fr, rho, x, y): source §4.10.3; exact kernel and final projection."""
Add(fx, fy, fr, rho, x, y) = P.scalar(P.add, (fx, fy), fr, rho, (x, y))
public Add
"""ScaledAdd: singleton block semantics with one final projection."""
ScaledAdd(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.add, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockAdd: positional elementwise semantics, retaining result scale s."""
BlockAdd(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) =
    P.block_apply(P.add, n, ((fs1, f1), (fs2, f2)), fs, fr, rho, ((s1, cs1), (s2, cs2)), s)
public ScaledAdd, BlockAdd

"""Subtract(fx, fy, fr, rho, x, y): source §4.10.3; exact kernel and final projection."""
Subtract(fx, fy, fr, rho, x, y) = P.scalar(P.subtract, (fx, fy), fr, rho, (x, y))
public Subtract
"""ScaledSubtract: singleton block semantics with one final projection."""
ScaledSubtract(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.subtract, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockSubtract: positional elementwise semantics, retaining result scale s."""
BlockSubtract(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) =
    P.block_apply(P.subtract, n, ((fs1, f1), (fs2, f2)), fs, fr, rho, ((s1, cs1), (s2, cs2)), s)
public ScaledSubtract, BlockSubtract

"""Multiply(fx, fy, fr, rho, x, y): source §4.10.4; exact kernel and final projection."""
Multiply(fx, fy, fr, rho, x, y) = P.scalar(P.multiply, (fx, fy), fr, rho, (x, y))
public Multiply
"""ScaledMultiply: singleton block semantics with one final projection."""
ScaledMultiply(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.multiply, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockMultiply: positional elementwise semantics, retaining result scale s."""
BlockMultiply(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) =
    P.block_apply(P.multiply, n, ((fs1, f1), (fs2, f2)), fs, fr, rho, ((s1, cs1), (s2, cs2)), s)
public ScaledMultiply, BlockMultiply

"""Divide(fx, fy, fr, rho, x, y): source §4.10.5; exact kernel and final projection."""
Divide(fx, fy, fr, rho, x, y) = P.scalar(P.divide, (fx, fy), fr, rho, (x, y))
public Divide
"""ScaledDivide: singleton block semantics with one final projection."""
ScaledDivide(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.divide, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockDivide: positional elementwise semantics, retaining result scale s."""
BlockDivide(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) =
    P.block_apply(P.divide, n, ((fs1, f1), (fs2, f2)), fs, fr, rho, ((s1, cs1), (s2, cs2)), s)
public ScaledDivide, BlockDivide

"""FMA(fx, fy, fz, fr, rho, x, y, z): source §4.10.6; exact kernel and final projection."""
FMA(fx, fy, fz, fr, rho, x, y, z) = P.scalar(P.fused_multiply_add, (fx, fy, fz), fr, rho, (x, y, z))
public FMA
"""ScaledFMA: singleton block semantics with one final projection."""
ScaledFMA(fs1, f1, fs2, f2, fs3, f3, fr, rho, s1, c1, s2, c2, s3, c3) = P.scaled(
    P.fused_multiply_add,
    ((fs1, f1), (fs2, f2), (fs3, f3)),
    fr,
    rho,
    ((s1, c1), (s2, c2), (s3, c3)),
)
"""BlockFMA: positional elementwise semantics, retaining result scale s."""
BlockFMA(n, fs1, f1, fs2, f2, fs3, f3, fs, fr, rho, s1, cs1, s2, cs2, s3, cs3, s) = P.block_apply(
    P.fused_multiply_add,
    n,
    ((fs1, f1), (fs2, f2), (fs3, f3)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2), (s3, cs3)),
    s,
)
public ScaledFMA, BlockFMA

"""FAA(fx, fy, fz, fr, rho, x, y, z): source §4.10.7; exact kernel and final projection."""
FAA(fx, fy, fz, fr, rho, x, y, z) = P.scalar(P.fused_add_add, (fx, fy, fz), fr, rho, (x, y, z))
public FAA
"""ScaledFAA: singleton block semantics with one final projection."""
ScaledFAA(fs1, f1, fs2, f2, fs3, f3, fr, rho, s1, c1, s2, c2, s3, c3) = P.scaled(
    P.fused_add_add,
    ((fs1, f1), (fs2, f2), (fs3, f3)),
    fr,
    rho,
    ((s1, c1), (s2, c2), (s3, c3)),
)
"""BlockFAA: positional elementwise semantics, retaining result scale s."""
BlockFAA(n, fs1, f1, fs2, f2, fs3, f3, fs, fr, rho, s1, cs1, s2, cs2, s3, cs3, s) = P.block_apply(
    P.fused_add_add,
    n,
    ((fs1, f1), (fs2, f2), (fs3, f3)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2), (s3, cs3)),
    s,
)
public ScaledFAA, BlockFAA

"""Sqrt(fx, fr, rho, x): source §4.10.8; exact kernel and final projection."""
Sqrt(fx, fr, rho, x) = P.scalar(P.sqrt_value, (fx,), fr, rho, (x,))
public Sqrt
"""ScaledSqrt: singleton block semantics with one final projection."""
ScaledSqrt(fs1, f1, fr, rho, s1, c1) = P.scaled(P.sqrt_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockSqrt: positional elementwise semantics, retaining result scale s."""
BlockSqrt(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.sqrt_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledSqrt, BlockSqrt

"""Recip(fx, fr, rho, x): source §4.10.8; exact kernel and final projection."""
Recip(fx, fr, rho, x) = P.scalar(P.reciprocal, (fx,), fr, rho, (x,))
public Recip
"""ScaledRecip: singleton block semantics with one final projection."""
ScaledRecip(fs1, f1, fr, rho, s1, c1) = P.scaled(P.reciprocal, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockRecip: positional elementwise semantics, retaining result scale s."""
BlockRecip(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.reciprocal, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledRecip, BlockRecip

"""RSqrt(fx, fr, rho, x): source §4.10.8; exact kernel and final projection."""
RSqrt(fx, fr, rho, x) = P.scalar(P.r_sqrt_value, (fx,), fr, rho, (x,))
public RSqrt
"""ScaledRSqrt: singleton block semantics with one final projection."""
ScaledRSqrt(fs1, f1, fr, rho, s1, c1) = P.scaled(P.r_sqrt_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockRSqrt: positional elementwise semantics, retaining result scale s."""
BlockRSqrt(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.r_sqrt_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledRSqrt, BlockRSqrt

"""Exp(fx, fr, rho, x): source §4.10.9; exact kernel and final projection."""
Exp(fx, fr, rho, x) = P.scalar(P.exp_value, (fx,), fr, rho, (x,))
public Exp
"""ScaledExp: singleton block semantics with one final projection."""
ScaledExp(fs1, f1, fr, rho, s1, c1) = P.scaled(P.exp_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockExp: positional elementwise semantics, retaining result scale s."""
BlockExp(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.exp_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledExp, BlockExp

"""Exp2(fx, fr, rho, x): source §4.10.9; exact kernel and final projection."""
Exp2(fx, fr, rho, x) = P.scalar(P.exp2_value, (fx,), fr, rho, (x,))
public Exp2
"""ScaledExp2: singleton block semantics with one final projection."""
ScaledExp2(fs1, f1, fr, rho, s1, c1) = P.scaled(P.exp2_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockExp2: positional elementwise semantics, retaining result scale s."""
BlockExp2(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.exp2_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledExp2, BlockExp2

"""Log(fx, fr, rho, x): source §4.10.9; exact kernel and final projection."""
Log(fx, fr, rho, x) = P.scalar(P.log_value, (fx,), fr, rho, (x,))
public Log
"""ScaledLog: singleton block semantics with one final projection."""
ScaledLog(fs1, f1, fr, rho, s1, c1) = P.scaled(P.log_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockLog: positional elementwise semantics, retaining result scale s."""
BlockLog(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.log_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledLog, BlockLog

"""Log2(fx, fr, rho, x): source §4.10.9; exact kernel and final projection."""
Log2(fx, fr, rho, x) = P.scalar(P.log2_value, (fx,), fr, rho, (x,))
public Log2
"""ScaledLog2: singleton block semantics with one final projection."""
ScaledLog2(fs1, f1, fr, rho, s1, c1) = P.scaled(P.log2_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockLog2: positional elementwise semantics, retaining result scale s."""
BlockLog2(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.log2_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledLog2, BlockLog2

"""LogOnePlus(fx, fr, rho, x): source §4.10.9; exact kernel and final projection."""
LogOnePlus(fx, fr, rho, x) = P.scalar(P.log_one_plus_value, (fx,), fr, rho, (x,))
public LogOnePlus
"""ScaledLogOnePlus: singleton block semantics with one final projection."""
ScaledLogOnePlus(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.log_one_plus_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockLogOnePlus: positional elementwise semantics, retaining result scale s."""
BlockLogOnePlus(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.log_one_plus_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledLogOnePlus, BlockLogOnePlus

"""ExpMinusOne(fx, fr, rho, x): source §4.10.9; exact kernel and final projection."""
ExpMinusOne(fx, fr, rho, x) = P.scalar(P.exp_minus_one_value, (fx,), fr, rho, (x,))
public ExpMinusOne
"""ScaledExpMinusOne: singleton block semantics with one final projection."""
ScaledExpMinusOne(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.exp_minus_one_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockExpMinusOne: positional elementwise semantics, retaining result scale s."""
BlockExpMinusOne(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.exp_minus_one_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledExpMinusOne, BlockExpMinusOne

"""Sin(fx, fr, rho, x): source §4.10.10; exact kernel and final projection."""
Sin(fx, fr, rho, x) = P.scalar(P.sin_value, (fx,), fr, rho, (x,))
public Sin
"""ScaledSin: singleton block semantics with one final projection."""
ScaledSin(fs1, f1, fr, rho, s1, c1) = P.scaled(P.sin_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockSin: positional elementwise semantics, retaining result scale s."""
BlockSin(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.sin_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledSin, BlockSin

"""Cos(fx, fr, rho, x): source §4.10.10; exact kernel and final projection."""
Cos(fx, fr, rho, x) = P.scalar(P.cos_value, (fx,), fr, rho, (x,))
public Cos
"""ScaledCos: singleton block semantics with one final projection."""
ScaledCos(fs1, f1, fr, rho, s1, c1) = P.scaled(P.cos_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockCos: positional elementwise semantics, retaining result scale s."""
BlockCos(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.cos_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledCos, BlockCos

"""Tan(fx, fr, rho, x): source §4.10.10; exact kernel and final projection."""
Tan(fx, fr, rho, x) = P.scalar(P.tan_value, (fx,), fr, rho, (x,))
public Tan
"""ScaledTan: singleton block semantics with one final projection."""
ScaledTan(fs1, f1, fr, rho, s1, c1) = P.scaled(P.tan_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockTan: positional elementwise semantics, retaining result scale s."""
BlockTan(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.tan_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledTan, BlockTan

"""ArcSin(fx, fr, rho, x): source §4.10.10; exact kernel and final projection."""
ArcSin(fx, fr, rho, x) = P.scalar(P.arc_sin_value, (fx,), fr, rho, (x,))
public ArcSin
"""ScaledArcSin: singleton block semantics with one final projection."""
ScaledArcSin(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.arc_sin_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockArcSin: positional elementwise semantics, retaining result scale s."""
BlockArcSin(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.arc_sin_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledArcSin, BlockArcSin

"""ArcCos(fx, fr, rho, x): source §4.10.10; exact kernel and final projection."""
ArcCos(fx, fr, rho, x) = P.scalar(P.arc_cos_value, (fx,), fr, rho, (x,))
public ArcCos
"""ScaledArcCos: singleton block semantics with one final projection."""
ScaledArcCos(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.arc_cos_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockArcCos: positional elementwise semantics, retaining result scale s."""
BlockArcCos(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.arc_cos_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledArcCos, BlockArcCos

"""ArcTan(fx, fr, rho, x): source §4.10.10; exact kernel and final projection."""
ArcTan(fx, fr, rho, x) = P.scalar(P.arc_tan_value, (fx,), fr, rho, (x,))
public ArcTan
"""ScaledArcTan: singleton block semantics with one final projection."""
ScaledArcTan(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.arc_tan_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockArcTan: positional elementwise semantics, retaining result scale s."""
BlockArcTan(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.arc_tan_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledArcTan, BlockArcTan

"""Sinh(fx, fr, rho, x): source §4.10.11; exact kernel and final projection."""
Sinh(fx, fr, rho, x) = P.scalar(P.sinh_value, (fx,), fr, rho, (x,))
public Sinh
"""ScaledSinh: singleton block semantics with one final projection."""
ScaledSinh(fs1, f1, fr, rho, s1, c1) = P.scaled(P.sinh_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockSinh: positional elementwise semantics, retaining result scale s."""
BlockSinh(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.sinh_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledSinh, BlockSinh

"""Cosh(fx, fr, rho, x): source §4.10.11; exact kernel and final projection."""
Cosh(fx, fr, rho, x) = P.scalar(P.cosh_value, (fx,), fr, rho, (x,))
public Cosh
"""ScaledCosh: singleton block semantics with one final projection."""
ScaledCosh(fs1, f1, fr, rho, s1, c1) = P.scaled(P.cosh_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockCosh: positional elementwise semantics, retaining result scale s."""
BlockCosh(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.cosh_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledCosh, BlockCosh

"""Tanh(fx, fr, rho, x): source §4.10.11; exact kernel and final projection."""
Tanh(fx, fr, rho, x) = P.scalar(P.tanh_value, (fx,), fr, rho, (x,))
public Tanh
"""ScaledTanh: singleton block semantics with one final projection."""
ScaledTanh(fs1, f1, fr, rho, s1, c1) = P.scaled(P.tanh_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockTanh: positional elementwise semantics, retaining result scale s."""
BlockTanh(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.tanh_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledTanh, BlockTanh

"""ArcSinh(fx, fr, rho, x): source §4.10.11; exact kernel and final projection."""
ArcSinh(fx, fr, rho, x) = P.scalar(P.arc_sinh_value, (fx,), fr, rho, (x,))
public ArcSinh
"""ScaledArcSinh: singleton block semantics with one final projection."""
ScaledArcSinh(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.arc_sinh_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockArcSinh: positional elementwise semantics, retaining result scale s."""
BlockArcSinh(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.arc_sinh_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledArcSinh, BlockArcSinh

"""ArcCosh(fx, fr, rho, x): source §4.10.11; exact kernel and final projection."""
ArcCosh(fx, fr, rho, x) = P.scalar(P.arc_cosh_value, (fx,), fr, rho, (x,))
public ArcCosh
"""ScaledArcCosh: singleton block semantics with one final projection."""
ScaledArcCosh(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.arc_cosh_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockArcCosh: positional elementwise semantics, retaining result scale s."""
BlockArcCosh(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.arc_cosh_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledArcCosh, BlockArcCosh

"""ArcTanh(fx, fr, rho, x): source §4.10.11; exact kernel and final projection."""
ArcTanh(fx, fr, rho, x) = P.scalar(P.arc_tanh_value, (fx,), fr, rho, (x,))
public ArcTanh
"""ScaledArcTanh: singleton block semantics with one final projection."""
ScaledArcTanh(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.arc_tanh_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockArcTanh: positional elementwise semantics, retaining result scale s."""
BlockArcTanh(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.arc_tanh_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledArcTanh, BlockArcTanh

"""SinPi(fx, fr, rho, x): source §4.10.12; exact kernel and final projection."""
SinPi(fx, fr, rho, x) = P.scalar(P.sin_pi_value, (fx,), fr, rho, (x,))
public SinPi
"""ScaledSinPi: singleton block semantics with one final projection."""
ScaledSinPi(fs1, f1, fr, rho, s1, c1) = P.scaled(P.sin_pi_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockSinPi: positional elementwise semantics, retaining result scale s."""
BlockSinPi(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.sin_pi_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledSinPi, BlockSinPi

"""CosPi(fx, fr, rho, x): source §4.10.12; exact kernel and final projection."""
CosPi(fx, fr, rho, x) = P.scalar(P.cos_pi_value, (fx,), fr, rho, (x,))
public CosPi
"""ScaledCosPi: singleton block semantics with one final projection."""
ScaledCosPi(fs1, f1, fr, rho, s1, c1) = P.scaled(P.cos_pi_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockCosPi: positional elementwise semantics, retaining result scale s."""
BlockCosPi(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.cos_pi_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledCosPi, BlockCosPi

"""TanPi(fx, fr, rho, x): source §4.10.12; exact kernel and final projection."""
TanPi(fx, fr, rho, x) = P.scalar(P.tan_pi_value, (fx,), fr, rho, (x,))
public TanPi
"""ScaledTanPi: singleton block semantics with one final projection."""
ScaledTanPi(fs1, f1, fr, rho, s1, c1) = P.scaled(P.tan_pi_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockTanPi: positional elementwise semantics, retaining result scale s."""
BlockTanPi(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.tan_pi_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledTanPi, BlockTanPi

"""ArcSinPi(fx, fr, rho, x): source §4.10.12; exact kernel and final projection."""
ArcSinPi(fx, fr, rho, x) = P.scalar(P.arc_sin_pi_value, (fx,), fr, rho, (x,))
public ArcSinPi
"""ScaledArcSinPi: singleton block semantics with one final projection."""
ScaledArcSinPi(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.arc_sin_pi_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockArcSinPi: positional elementwise semantics, retaining result scale s."""
BlockArcSinPi(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.arc_sin_pi_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledArcSinPi, BlockArcSinPi

"""ArcCosPi(fx, fr, rho, x): source §4.10.12; exact kernel and final projection."""
ArcCosPi(fx, fr, rho, x) = P.scalar(P.arc_cos_pi_value, (fx,), fr, rho, (x,))
public ArcCosPi
"""ScaledArcCosPi: singleton block semantics with one final projection."""
ScaledArcCosPi(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.arc_cos_pi_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockArcCosPi: positional elementwise semantics, retaining result scale s."""
BlockArcCosPi(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.arc_cos_pi_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledArcCosPi, BlockArcCosPi

"""ArcTanPi(fx, fr, rho, x): source §4.10.12; exact kernel and final projection."""
ArcTanPi(fx, fr, rho, x) = P.scalar(P.arc_tan_pi_value, (fx,), fr, rho, (x,))
public ArcTanPi
"""ScaledArcTanPi: singleton block semantics with one final projection."""
ScaledArcTanPi(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.arc_tan_pi_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockArcTanPi: positional elementwise semantics, retaining result scale s."""
BlockArcTanPi(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.arc_tan_pi_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledArcTanPi, BlockArcTanPi

"""Softplus(fx, fr, rho, x): source §4.10.13; exact kernel and final projection."""
Softplus(fx, fr, rho, x) = P.scalar(P.softplus_value, (fx,), fr, rho, (x,))
public Softplus
"""ScaledSoftplus: singleton block semantics with one final projection."""
ScaledSoftplus(fs1, f1, fr, rho, s1, c1) =
    P.scaled(P.softplus_value, ((fs1, f1),), fr, rho, ((s1, c1),))
"""BlockSoftplus: positional elementwise semantics, retaining result scale s."""
BlockSoftplus(n, fs1, f1, fs, fr, rho, s1, cs1, s) =
    P.block_apply(P.softplus_value, n, ((fs1, f1),), fs, fr, rho, ((s1, cs1),), s)
public ScaledSoftplus, BlockSoftplus

"""Hypot(fx, fy, fr, rho, x, y): source §4.10.14; exact kernel and final projection."""
Hypot(fx, fy, fr, rho, x, y) = P.scalar(P.hypot_value, (fx, fy), fr, rho, (x, y))
public Hypot
"""ScaledHypot: singleton block semantics with one final projection."""
ScaledHypot(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.hypot_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockHypot: positional elementwise semantics, retaining result scale s."""
BlockHypot(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) =
    P.block_apply(P.hypot_value, n, ((fs1, f1), (fs2, f2)), fs, fr, rho, ((s1, cs1), (s2, cs2)), s)
public ScaledHypot, BlockHypot

"""ArcTan2(fy, fx, fr, rho, y, x): source §4.10.15; exact kernel and final projection."""
ArcTan2(fy, fx, fr, rho, y, x) = P.scalar(P.atan2_value, (fy, fx), fr, rho, (y, x))
public ArcTan2
"""ScaledArcTan2: singleton block semantics with one final projection."""
ScaledArcTan2(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.atan2_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockArcTan2: positional elementwise semantics, retaining result scale s."""
BlockArcTan2(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) =
    P.block_apply(P.atan2_value, n, ((fs1, f1), (fs2, f2)), fs, fr, rho, ((s1, cs1), (s2, cs2)), s)
public ScaledArcTan2, BlockArcTan2

"""ArcTan2Pi(fy, fx, fr, rho, y, x): source §4.10.16; exact kernel and final projection."""
ArcTan2Pi(fy, fx, fr, rho, y, x) = P.scalar(P.arc_tan2_pi_value, (fy, fx), fr, rho, (y, x))
public ArcTan2Pi
"""ScaledArcTan2Pi: singleton block semantics with one final projection."""
ScaledArcTan2Pi(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.arc_tan2_pi_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockArcTan2Pi: positional elementwise semantics, retaining result scale s."""
BlockArcTan2Pi(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.arc_tan2_pi_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledArcTan2Pi, BlockArcTan2Pi

"""Minimum(fx, fy, fr, rho, x, y): source §4.11.1; exact kernel and final projection."""
Minimum(fx, fy, fr, rho, x, y) = P.scalar(P.minimum_value, (fx, fy), fr, rho, (x, y))
public Minimum
"""ScaledMinimum: singleton block semantics with one final projection."""
ScaledMinimum(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.minimum_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockMinimum: positional elementwise semantics, retaining result scale s."""
BlockMinimum(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.minimum_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledMinimum, BlockMinimum

"""Maximum(fx, fy, fr, rho, x, y): source §4.11.1; exact kernel and final projection."""
Maximum(fx, fy, fr, rho, x, y) = P.scalar(P.maximum_value, (fx, fy), fr, rho, (x, y))
public Maximum
"""ScaledMaximum: singleton block semantics with one final projection."""
ScaledMaximum(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.maximum_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockMaximum: positional elementwise semantics, retaining result scale s."""
BlockMaximum(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.maximum_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledMaximum, BlockMaximum

"""MinimumNumber(fx, fy, fr, rho, x, y): source §4.11.1; exact kernel and final projection."""
MinimumNumber(fx, fy, fr, rho, x, y) = P.scalar(P.minimum_number_value, (fx, fy), fr, rho, (x, y))
public MinimumNumber
"""ScaledMinimumNumber: singleton block semantics with one final projection."""
ScaledMinimumNumber(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.minimum_number_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockMinimumNumber: positional elementwise semantics, retaining result scale s."""
BlockMinimumNumber(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.minimum_number_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledMinimumNumber, BlockMinimumNumber

"""MaximumNumber(fx, fy, fr, rho, x, y): source §4.11.1; exact kernel and final projection."""
MaximumNumber(fx, fy, fr, rho, x, y) = P.scalar(P.maximum_number_value, (fx, fy), fr, rho, (x, y))
public MaximumNumber
"""ScaledMaximumNumber: singleton block semantics with one final projection."""
ScaledMaximumNumber(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.maximum_number_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockMaximumNumber: positional elementwise semantics, retaining result scale s."""
BlockMaximumNumber(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.maximum_number_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledMaximumNumber, BlockMaximumNumber

"""MinimumMagnitude(fx, fy, fr, rho, x, y): source §4.11.2; exact kernel and final projection."""
MinimumMagnitude(fx, fy, fr, rho, x, y) =
    P.scalar(P.minimum_magnitude_value, (fx, fy), fr, rho, (x, y))
public MinimumMagnitude
"""ScaledMinimumMagnitude: singleton block semantics with one final projection."""
ScaledMinimumMagnitude(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.minimum_magnitude_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockMinimumMagnitude: positional elementwise semantics, retaining result scale s."""
BlockMinimumMagnitude(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.minimum_magnitude_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledMinimumMagnitude, BlockMinimumMagnitude

"""MaximumMagnitude(fx, fy, fr, rho, x, y): source §4.11.2; exact kernel and final projection."""
MaximumMagnitude(fx, fy, fr, rho, x, y) =
    P.scalar(P.maximum_magnitude_value, (fx, fy), fr, rho, (x, y))
public MaximumMagnitude
"""ScaledMaximumMagnitude: singleton block semantics with one final projection."""
ScaledMaximumMagnitude(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.maximum_magnitude_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockMaximumMagnitude: positional elementwise semantics, retaining result scale s."""
BlockMaximumMagnitude(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.maximum_magnitude_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledMaximumMagnitude, BlockMaximumMagnitude

"""MinimumMagnitudeNumber(fx, fy, fr, rho, x, y): source §4.11.2; exact kernel and final projection."""
MinimumMagnitudeNumber(fx, fy, fr, rho, x, y) =
    P.scalar(P.minimum_magnitude_number_value, (fx, fy), fr, rho, (x, y))
public MinimumMagnitudeNumber
"""ScaledMinimumMagnitudeNumber: singleton block semantics with one final projection."""
ScaledMinimumMagnitudeNumber(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) = P.scaled(
    P.minimum_magnitude_number_value,
    ((fs1, f1), (fs2, f2)),
    fr,
    rho,
    ((s1, c1), (s2, c2)),
)
"""BlockMinimumMagnitudeNumber: positional elementwise semantics, retaining result scale s."""
BlockMinimumMagnitudeNumber(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.minimum_magnitude_number_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledMinimumMagnitudeNumber, BlockMinimumMagnitudeNumber

"""MaximumMagnitudeNumber(fx, fy, fr, rho, x, y): source §4.11.2; exact kernel and final projection."""
MaximumMagnitudeNumber(fx, fy, fr, rho, x, y) =
    P.scalar(P.maximum_magnitude_number_value, (fx, fy), fr, rho, (x, y))
public MaximumMagnitudeNumber
"""ScaledMaximumMagnitudeNumber: singleton block semantics with one final projection."""
ScaledMaximumMagnitudeNumber(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) = P.scaled(
    P.maximum_magnitude_number_value,
    ((fs1, f1), (fs2, f2)),
    fr,
    rho,
    ((s1, c1), (s2, c2)),
)
"""BlockMaximumMagnitudeNumber: positional elementwise semantics, retaining result scale s."""
BlockMaximumMagnitudeNumber(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.maximum_magnitude_number_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledMaximumMagnitudeNumber, BlockMaximumMagnitudeNumber

"""MinimumFinite(fx, fy, fr, rho, x, y): source §4.11.3; exact kernel and final projection."""
MinimumFinite(fx, fy, fr, rho, x, y) = P.scalar(P.minimum_finite_value, (fx, fy), fr, rho, (x, y))
public MinimumFinite
"""ScaledMinimumFinite: singleton block semantics with one final projection."""
ScaledMinimumFinite(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.minimum_finite_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockMinimumFinite: positional elementwise semantics, retaining result scale s."""
BlockMinimumFinite(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.minimum_finite_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledMinimumFinite, BlockMinimumFinite

"""MaximumFinite(fx, fy, fr, rho, x, y): source §4.11.3; exact kernel and final projection."""
MaximumFinite(fx, fy, fr, rho, x, y) = P.scalar(P.maximum_finite_value, (fx, fy), fr, rho, (x, y))
public MaximumFinite
"""ScaledMaximumFinite: singleton block semantics with one final projection."""
ScaledMaximumFinite(fs1, f1, fs2, f2, fr, rho, s1, c1, s2, c2) =
    P.scaled(P.maximum_finite_value, ((fs1, f1), (fs2, f2)), fr, rho, ((s1, c1), (s2, c2)))
"""BlockMaximumFinite: positional elementwise semantics, retaining result scale s."""
BlockMaximumFinite(n, fs1, f1, fs2, f2, fs, fr, rho, s1, cs1, s2, cs2, s) = P.block_apply(
    P.maximum_finite_value,
    n,
    ((fs1, f1), (fs2, f2)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2)),
    s,
)
public ScaledMaximumFinite, BlockMaximumFinite

"""Clamp(fx, flo, fhi, fr, rho, x, lo, hi): source §4.11.4; exact kernel and final projection."""
Clamp(fx, flo, fhi, fr, rho, x, lo, hi) =
    P.scalar(P.clamp_value, (fx, flo, fhi), fr, rho, (x, lo, hi))
public Clamp
"""ScaledClamp: singleton block semantics with one final projection."""
ScaledClamp(fs1, f1, fs2, f2, fs3, f3, fr, rho, s1, c1, s2, c2, s3, c3) = P.scaled(
    P.clamp_value,
    ((fs1, f1), (fs2, f2), (fs3, f3)),
    fr,
    rho,
    ((s1, c1), (s2, c2), (s3, c3)),
)
"""BlockClamp: positional elementwise semantics, retaining result scale s."""
BlockClamp(n, fs1, f1, fs2, f2, fs3, f3, fs, fr, rho, s1, cs1, s2, cs2, s3, cs3, s) = P.block_apply(
    P.clamp_value,
    n,
    ((fs1, f1), (fs2, f2), (fs3, f3)),
    fs,
    fr,
    rho,
    ((s1, cs1), (s2, cs2), (s3, cs3)),
    s,
)
public ScaledClamp, BlockClamp

