# Generated by tools/generate.jl; do not edit.
# Input SHA256: ebb8032d469a051dcee21389ea8461ad8f03b32900a9e94f426b4db64a5adc77
sqrt_value(x) = elementary(:Sqrt, x)
r_sqrt_value(x) = elementary(:RSqrt, x)
exp_value(x) = elementary(:Exp, x)
exp2_value(x) = elementary(:Exp2, x)
log_value(x) = elementary(:Log, x)
log2_value(x) = elementary(:Log2, x)
log_one_plus_value(x) = elementary(:LogOnePlus, x)
exp_minus_one_value(x) = elementary(:ExpMinusOne, x)
sin_value(x) = elementary(:Sin, x)
cos_value(x) = elementary(:Cos, x)
tan_value(x) = elementary(:Tan, x)
arc_sin_value(x) = elementary(:ArcSin, x)
arc_cos_value(x) = elementary(:ArcCos, x)
arc_tan_value(x) = elementary(:ArcTan, x)
sinh_value(x) = elementary(:Sinh, x)
cosh_value(x) = elementary(:Cosh, x)
tanh_value(x) = elementary(:Tanh, x)
arc_sinh_value(x) = elementary(:ArcSinh, x)
arc_cosh_value(x) = elementary(:ArcCosh, x)
arc_tanh_value(x) = elementary(:ArcTanh, x)
sin_pi_value(x) = elementary(:SinPi, x)
cos_pi_value(x) = elementary(:CosPi, x)
tan_pi_value(x) = elementary(:TanPi, x)
arc_sin_pi_value(x) = elementary(:ArcSinPi, x)
arc_cos_pi_value(x) = elementary(:ArcCosPi, x)
arc_tan_pi_value(x) = elementary(:ArcTanPi, x)
softplus_value(x) = elementary(:Softplus, x)
arc_tan2_pi_value(y, x) = divide(atan2_value(y, x), PI)
minimum_value(x, y) =
    extrema(x, y; maximum = false, number = false, finite_only = false, by_magnitude = false)
maximum_value(x, y) =
    extrema(x, y; maximum = true, number = false, finite_only = false, by_magnitude = false)
minimum_number_value(x, y) =
    extrema(x, y; maximum = false, number = true, finite_only = false, by_magnitude = false)
maximum_number_value(x, y) =
    extrema(x, y; maximum = true, number = true, finite_only = false, by_magnitude = false)
minimum_magnitude_value(x, y) =
    extrema(x, y; maximum = false, number = false, finite_only = false, by_magnitude = true)
maximum_magnitude_value(x, y) =
    extrema(x, y; maximum = true, number = false, finite_only = false, by_magnitude = true)
minimum_magnitude_number_value(x, y) =
    extrema(x, y; maximum = false, number = true, finite_only = false, by_magnitude = true)
maximum_magnitude_number_value(x, y) =
    extrema(x, y; maximum = true, number = true, finite_only = false, by_magnitude = true)
minimum_finite_value(x, y) =
    extrema(x, y; maximum = false, number = false, finite_only = true, by_magnitude = false)
maximum_finite_value(x, y) =
    extrema(x, y; maximum = true, number = false, finite_only = true, by_magnitude = false)
const OPERATION_KERNELS = (
    Convert = identity,
    Abs = magnitude,
    Negate = negate,
    CopySign = copy_sign,
    Add = add,
    Subtract = subtract,
    Multiply = multiply,
    Divide = divide,
    FMA = fused_multiply_add,
    FAA = fused_add_add,
    Sqrt = sqrt_value,
    Recip = reciprocal,
    RSqrt = r_sqrt_value,
    Exp = exp_value,
    Exp2 = exp2_value,
    Log = log_value,
    Log2 = log2_value,
    LogOnePlus = log_one_plus_value,
    ExpMinusOne = exp_minus_one_value,
    Sin = sin_value,
    Cos = cos_value,
    Tan = tan_value,
    ArcSin = arc_sin_value,
    ArcCos = arc_cos_value,
    ArcTan = arc_tan_value,
    Sinh = sinh_value,
    Cosh = cosh_value,
    Tanh = tanh_value,
    ArcSinh = arc_sinh_value,
    ArcCosh = arc_cosh_value,
    ArcTanh = arc_tanh_value,
    SinPi = sin_pi_value,
    CosPi = cos_pi_value,
    TanPi = tan_pi_value,
    ArcSinPi = arc_sin_pi_value,
    ArcCosPi = arc_cos_pi_value,
    ArcTanPi = arc_tan_pi_value,
    Softplus = softplus_value,
    Hypot = hypot_value,
    ArcTan2 = atan2_value,
    ArcTan2Pi = arc_tan2_pi_value,
    Minimum = minimum_value,
    Maximum = maximum_value,
    MinimumNumber = minimum_number_value,
    MaximumNumber = maximum_number_value,
    MinimumMagnitude = minimum_magnitude_value,
    MaximumMagnitude = maximum_magnitude_value,
    MinimumMagnitudeNumber = minimum_magnitude_number_value,
    MaximumMagnitudeNumber = maximum_magnitude_number_value,
    MinimumFinite = minimum_finite_value,
    MaximumFinite = maximum_finite_value,
    Clamp = clamp_value,
)
