indent = 4
margin = 92
normalize_line_endings = "unix"
trailing_zero = true
surround_whereop_typeparameters = true
indent_submodule=true
indent_submodule_in_method=true
separate_kwargs_with_semicolon=true
for_in_replacement = "∈"
join_lines_based_on_source = true
# overwrite = true
format_markdown = true
always_for_in = true
whitespace_ops_in_indices = true
whitespace_typedefs = true
whitespace_ops_in_call = true
remove_extra_blank_lines = true
remove_extra_newlines = true
