# .JuliaFormatter.toml

# text;
# style = DefaultStyle()
margin = 78
indent = 4

normalize_line_endings = "unix"

align_assignment = true
align_conditional = true
align_matrix = true
align_pair_arrow = true
align_struct_field = true

always_for_in = true
for_in_replacement = "in"

always_use_return = false
annotate_untyped_fields_with_any = true
conditional_to_if = false
disallow_single_arg_nesting = false

format_docstrings = false
import_to_using = false
indent_submodule = true
join_lines_based_on_source = false
pipe_to_function_call = false

remove_extra_newlines = true
separate_kwargs_with_semicolon = true

short_circuit_to_if = false

long_to_short_function_def = false
short_to_long_function_def = false

surround_whereop_typeparameters = true

trailing_comma = false
trailing_zero = true

variable_call_indent = []
whitespace_in_kwargs = true
whitespace_ops_in_indices = true
whitespace_typedefs = true
