name = "AIFloats"
uuid = "7efd15cf-1a78-48fa-8306-a9f4f4535af3"
authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@gmail.org>"]
version = "0.1.0"

[deps]
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
AlignedAllocs = "6ac60441-711f-43f0-8178-7f71f0888134"
Quadmath =  "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"

[compat]
Static = "1.2"
AlignedAllocs = "0.1.12 - 0.1.40"
Quadmath = "0.5 - 0.9"
Test = "1.10"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
