#!/usr/bin/env python3
"""Generate only scalar, elementwise and scaled schemas from the inventory."""
import argparse,json,pathlib,sys
ROOT=pathlib.Path(__file__).resolve().parents[1]

def generate(profile,block):
    ops=[o for o in json.loads((ROOT/'inventory/operations.json').read_text())['operations'] if o.get('wrapper') and o['profile']==profile and o['result']=='code' and (o['block'] if block else True)]
    mod='P3109-'+('SYMBOLIC-' if profile=='symbolic' else '')+('BLOCK-WRAPPERS' if block else 'SCALAR')
    deps=['P3109-BLOCK'] if block else ['P3109-PROJECT','P3109-OMEGA-EXTREMA']
    if profile=='symbolic':deps+=['P3109-OMEGA-ELEMENTARY']
    out=['--- Generated by tools/generate-wrappers.py; edit inventory or generator.',f'fmod {mod} is']
    out += ['  including '+d+' .' for d in deps]
    out += ['  vars F1 F2 F3 FS1 FS2 FS3 FS FR : Format .','  vars C1 C2 C3 S1 S2 S3 S : Int .','  var PS : ProjSpec .']
    if block:out+=['  var B : Nat .','  var BP : BlockProjSpec .','  vars CS1 CS2 CS3 : CodeSeq .','  vars XS1 XS2 XS3 : XSeq .','  vars X1 X2 X3 : XReal .']
    for o in ops:
        name=o['name'];n=o['arity'];ids=range(1,n+1)
        fs=[f'F{i}' for i in ids];cs=[f'C{i}' for i in ids]
        meta=f'metadata "clause={o["clause"]}; page={o["pages"][0]}; schema='+('5.7-5.8' if block else '4.3.1')+'"'
        if not block:
            args=fs+['FR','PS']+cs
            body=f'project(FR, PS, omega{name}('+', '.join(f'decode(F{i}, C{i})' for i in ids)+'))'
            guards=[f'validCode(F{i}, C{i})' for i in ids]+['validFormat(FR)','validProjection(PS)']
            out += [f'  op {name} : '+('Format '*(n+1))+'ProjSpec '+('Int '*n)+'~> Nat .',f'  ceq [p3109-scalar-{name}] : {name}('+', '.join(args)+') = '+body+' if '+' /\\ '.join(guards)+f' [{meta}] .']
        else:
            fmt=[x for i in ids for x in [f'FS{i}',f'F{i}']];blocks=[x for i in ids for x in [f'S{i}',f'CS{i}']]
            args=['B']+fmt+['FS','FR','BP']+blocks+['S']
            maps=', '.join(f'blockDecode(B, FS{i}, F{i}, S{i}, CS{i})' for i in ids)
            guards=[f'validBlock(B, FS{i}, F{i}, S{i}, CS{i})' for i in ids]+['validCode(FS, S)','validFormat(FR)','validBlockProjection(BP, B)']
            out += [f'  op Block{name} : Nat '+('Format '*(2*n+2))+'BlockProjSpec '+('Int CodeSeq '*n)+'Int ~> Block .',f'  op map{name} : '+('XSeq '*n)+'~> XSeq .',f'  ceq [p3109-block-{name}] : Block{name}('+', '.join(args)+f') = block(S, blockProject(B, FS, FR, BP, S, map{name}({maps}))) if '+' /\\ '.join(guards)+f' [{meta}] .',f'  eq [p3109-map-{name}-nil] : map{name}('+', '.join(['xnil']*n)+f') = xnil [{meta}] .',f'  eq [p3109-map-{name}-cons] : map{name}('+', '.join(f'xcons(X{i}, XS{i})' for i in ids)+f') = xcons(omega{name}('+', '.join(f'X{i}' for i in ids)+f'), map{name}('+', '.join(f'XS{i}' for i in ids)+f')) [{meta}] .']
            # Singleton lift through the same block algorithm, with exactly encoded result scale 1.
            args=fmt+['FR','PS']+[x for i in ids for x in [f'S{i}',f'C{i}']]
            call=['1']+fmt+['Binary(4, 2, Signed, Finite)','FR','singletonLift(PS)']+[x for i in ids for x in [f'S{i}',f'ccons(C{i}, cnil)']]+['4']
            out += [f'  op Scaled{name} : '+('Format '*(2*n+1))+'ProjSpec '+('Int Int '*n)+'~> Nat .',f'  ceq [p3109-scaled-{name}] : Scaled{name}('+', '.join(args)+f') = scaledResult(Block{name}('+', '.join(call)+')) if '+' /\\ '.join([f'validCode(FS{i}, S{i}) /\\ validCode(F{i}, C{i})' for i in ids]+['validFormat(FR)','validProjection(PS)'])+f' [{meta}] .']
    return '\n'.join(out+['endfm',''])

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args()
    bad=[]
    for profile in ['core','symbolic']:
        for block in [False,True]:
            path=ROOT/('lib' if profile=='core' else 'symbolic')/('block-wrappers.maude' if block else 'scalar-ops.maude')
            text=generate(profile,block)
            if a.check:
                if not path.exists() or path.read_text()!=text:bad.append(str(path))
            else:path.write_text(text)
    if bad:sys.exit('Stale generated files: '+', '.join(bad))
    print('Wrappers verified.' if a.check else 'Wrappers generated.')
if __name__=='__main__':main()
