-- Extracted from ../spec2.lean, lines 20414-20919.
-- See PLAN.md and manifest.json for provenance.
import P3109.Lemmas.Rewriting.Strings

namespace Maude
-- String conversion

def kBoundQuery.repr : kBoundQuery → String
  | kBoundQuery.maxFiniteQuery => "maxFiniteQuery"
  | kBoundQuery.minFiniteQuery => "minFiniteQuery"
  | kBoundQuery.minPositiveQuery => "minPositiveQuery"
  | kBoundQuery.maxSubnormalQuery => "maxSubnormalQuery"
  | kBoundQuery.minNormalQuery => "minNormalQuery"

def kEvidence.repr : kEvidence → String
  | kEvidence.pendingEvidence => "pendingEvidence"
  | kEvidence.sampleEvidence => "sampleEvidence"
  | kEvidence.exhaustiveEvidence => "exhaustiveEvidence"
  | kEvidence.proofEvidence => "proofEvidence"

mutual

  def kArityEntry.repr : kArityEntry → String
    | (kArityEntry.entry a₀ a₁) => "entry(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kArityEntry.«at» a₀ a₁) => "at(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"

  def kArityTable.repr : kArityTable → String
    | kArityTable.anil => "anil"
    | (kArityTable.acons a₀ a₁) => "acons(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | kArityTable.numericArityTable => "numericArityTable"
    | kArityTable.plainArityTable => "plainArityTable"
    | kArityTable.blockElementArityTable => "blockElementArityTable"

  def kBlock.repr : kBlock → String
    | (kBlock.block a₀ a₁) => "block(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBlock.ConvertToBlockMaxAbsFinite a₀ a₁ a₂ a₃ a₄ a₅ a₆) => "ConvertToBlockMaxAbsFinite(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ")"
    | (kBlock.computedBlock a₀ a₁ a₂ a₃ a₄ a₅) => "computedBlock(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (reprStr a₄) ++ ", " ++ (a₅.repr) ++ ")"
    | (kBlock.BlockConvert a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockConvert(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockAbs a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockAbs(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockNegate a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockNegate(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockCopySign a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockCopySign(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockAdd a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockAdd(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockSubtract a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockSubtract(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockMultiply a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMultiply(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockDivide a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockDivide(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockFMA a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂ a₁₃ a₁₄ a₁₅ a₁₆) => "BlockFMA(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (a₈.repr) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ", " ++ (a₁₃.repr) ++ ", " ++ (reprStr a₁₄) ++ ", " ++ (a₁₅.repr) ++ ", " ++ (reprStr a₁₆) ++ ")"
    | (kBlock.BlockFAA a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂ a₁₃ a₁₄ a₁₅ a₁₆) => "BlockFAA(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (a₈.repr) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ", " ++ (a₁₃.repr) ++ ", " ++ (reprStr a₁₄) ++ ", " ++ (a₁₅.repr) ++ ", " ++ (reprStr a₁₆) ++ ")"
    | (kBlock.BlockRecip a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockRecip(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockMinimum a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMinimum(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockMaximum a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMaximum(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockMinimumNumber a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMinimumNumber(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockMaximumNumber a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMaximumNumber(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockMinimumMagnitude a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMinimumMagnitude(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockMaximumMagnitude a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMaximumMagnitude(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockMinimumMagnitudeNumber a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMinimumMagnitudeNumber(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockMaximumMagnitudeNumber a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMaximumMagnitudeNumber(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockMinimumFinite a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMinimumFinite(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockMaximumFinite a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockMaximumFinite(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockClamp a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂ a₁₃ a₁₄ a₁₅ a₁₆) => "BlockClamp(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (a₈.repr) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ", " ++ (a₁₃.repr) ++ ", " ++ (reprStr a₁₄) ++ ", " ++ (a₁₅.repr) ++ ", " ++ (reprStr a₁₆) ++ ")"
    | (kBlock.BlockSqrt a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockSqrt(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockRSqrt a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockRSqrt(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockExp a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockExp(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockExp2 a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockExp2(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockLog a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockLog(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockLog2 a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockLog2(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockLogOnePlus a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockLogOnePlus(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockExpMinusOne a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockExpMinusOne(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockSin a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockSin(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockCos a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockCos(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockTan a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockTan(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockArcSin a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockArcSin(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockArcCos a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockArcCos(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockArcTan a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockArcTan(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockSinh a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockSinh(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockCosh a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockCosh(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockTanh a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockTanh(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockArcSinh a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockArcSinh(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockArcCosh a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockArcCosh(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockArcTanh a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockArcTanh(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockSinPi a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockSinPi(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockCosPi a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockCosPi(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockTanPi a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockTanPi(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockArcSinPi a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockArcSinPi(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockArcCosPi a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockArcCosPi(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockArcTanPi a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockArcTanPi(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockSoftplus a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈) => "BlockSoftplus(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ")"
    | (kBlock.BlockHypot a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockHypot(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockArcTan2 a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockArcTan2(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"
    | (kBlock.BlockArcTan2Pi a₀ a₁ a₂ a₃ a₄ a₅ a₆ a₇ a₈ a₉ a₁₀ a₁₁ a₁₂) => "BlockArcTan2Pi(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ", " ++ (a₇.repr) ++ ", " ++ (reprStr a₈) ++ ", " ++ (a₉.repr) ++ ", " ++ (reprStr a₁₀) ++ ", " ++ (a₁₁.repr) ++ ", " ++ (reprStr a₁₂) ++ ")"

  def kBlockProjSpec.repr : kBlockProjSpec → String
    | (kBlockProjSpec.bproj a₀ a₁) => "bproj(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBlockProjSpec.singletonLift a) => "singletonLift(" ++ (a.repr) ++ ")"

  def kBlockRoundMode.repr : kBlockRoundMode → String
    | kBlockRoundMode.NearestTiesToEven => "NearestTiesToEven"
    | kBlockRoundMode.NearestTiesToAway => "NearestTiesToAway"
    | kBlockRoundMode.TowardPositive => "TowardPositive"
    | kBlockRoundMode.TowardNegative => "TowardNegative"
    | kBlockRoundMode.TowardZero => "TowardZero"
    | kBlockRoundMode.ToOdd => "ToOdd"
    | (kBlockRoundMode.StochasticA a₀ a₁) => "StochasticA(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBlockRoundMode.StochasticB a₀ a₁) => "StochasticB(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBlockRoundMode.StochasticC a₀ a₁) => "StochasticC(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBlockRoundMode.BlockStochasticA a₀ a₁) => "BlockStochasticA(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBlockRoundMode.BlockStochasticB a₀ a₁) => "BlockStochasticB(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBlockRoundMode.BlockStochasticC a₀ a₁) => "BlockStochasticC(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBlockRoundMode.RoundOf a) => "RoundOf(" ++ (a.repr) ++ ")"

  def kBool.repr : kBool → String
    | kBool.true => "true"
    | kBool.false => "false"
    | (kBool.and a₀ a₁) => "_and_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.or a₀ a₁) => "_or_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.xor a₀ a₁) => "_xor_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.not a) => "not_(" ++ (a.repr) ++ ")"
    | (kBool.implies a₀ a₁) => "_implies_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.lt₀ a₀ a₁) => "_<_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.lteq₀ a₀ a₁) => "_<=_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.gt₀ a₀ a₁) => "_>_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.gteq₀ a₀ a₁) => "_>=_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.divides a₀ a₁) => "_divides_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.xNaN a) => "xNaN(" ++ (a.repr) ++ ")"
    | (kBool.xInfinite a) => "xInfinite(" ++ (a.repr) ++ ")"
    | (kBool.xFinite a) => "xFinite(" ++ (a.repr) ++ ")"
    | (kBool.xMinus a) => "xMinus(" ++ (a.repr) ++ ")"
    | (kBool.xLt a₀ a₁) => "xLt(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.xLe a₀ a₁) => "xLe(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.xEq a₀ a₁) => "xEq(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.even a) => "even(" ++ (reprStr a) ++ ")"
    | (kBool.validFormat a) => "validFormat(" ++ (a.repr) ++ ")"
    | (kBool.internalFormat a) => "internalFormat(" ++ (a.repr) ++ ")"
    | (kBool.externalDatum a₀ a₁) => "externalDatum(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.validCode a₀ a₁) => "validCode(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.datum a₀ a₁) => "datum(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.candidateDatum a₀ a₁ a₂) => "candidateDatum(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ", " ++ (reprStr a₂) ++ ")"
    | (kBool.randomInRange a₀ a₁) => "randomInRange(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.validRound a) => "validRound(" ++ (a.repr) ++ ")"
    | (kBool.validProjection a) => "validProjection(" ++ (a.repr) ++ ")"
    | (kBool.validBlockProjection a₀ a₁) => "validBlockProjection(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.validRandoms a₀ a₁) => "validRandoms(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.deterministic a) => "deterministic(" ++ (a.repr) ++ ")"
    | (kBool.roundAway a₀ a₁ a₂ a₃) => "roundAway(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ", " ++ (reprStr a₂) ++ ", " ++ (a₃.repr) ++ ")"
    | (kBool.clipsHigh a) => "clipsHigh(" ++ (a.repr) ++ ")"
    | (kBool.clipsLow a) => "clipsLow(" ++ (a.repr) ++ ")"
    | (kBool.validCodes a₀ a₁) => "validCodes(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.validBlock a₀ a₁ a₂ a₃ a₄) => "validBlock(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (reprStr a₃) ++ ", " ++ (a₄.repr) ++ ")"
    | (kBool.lt₁ a₀ a₁) => "_<_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.lteq₁ a₀ a₁) => "_<=_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.gt₁ a₀ a₁) => "_>_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.gteq₁ a₀ a₁) => "_>=_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.CompareLess a₀ a₁ a₂ a₃) => "CompareLess(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (reprStr a₂) ++ ", " ++ (reprStr a₃) ++ ")"
    | (kBool.CompareLessEqual a₀ a₁ a₂ a₃) => "CompareLessEqual(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (reprStr a₂) ++ ", " ++ (reprStr a₃) ++ ")"
    | (kBool.CompareEqual a₀ a₁ a₂ a₃) => "CompareEqual(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (reprStr a₂) ++ ", " ++ (reprStr a₃) ++ ")"
    | (kBool.CompareGreaterEqual a₀ a₁ a₂ a₃) => "CompareGreaterEqual(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (reprStr a₂) ++ ", " ++ (reprStr a₃) ++ ")"
    | (kBool.CompareGreater a₀ a₁ a₂ a₃) => "CompareGreater(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (reprStr a₂) ++ ", " ++ (reprStr a₃) ++ ")"
    | (kBool.IsZero a₀ a₁) => "IsZero(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.IsOne a₀ a₁) => "IsOne(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.IsNaN a₀ a₁) => "IsNaN(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.IsInfinite a₀ a₁) => "IsInfinite(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.IsFinite a₀ a₁) => "IsFinite(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.IsSignMinus a₀ a₁) => "IsSignMinus(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.IsNormal a₀ a₁) => "IsNormal(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.IsSubnormal a₀ a₁) => "IsSubnormal(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.inF4 a) => "inF4(" ++ (a.repr) ++ ")"
    | (kBool.inF8 a) => "inF8(" ++ (a.repr) ++ ")"
    | (kBool.inFs a) => "inFs(" ++ (a.repr) ++ ")"
    | (kBool.allowedExternal a) => "allowedExternal(" ++ (a.repr) ++ ")"
    | (kBool.containsFormat a₀ a₁) => "containsFormat(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.validFX a) => "validFX(" ++ (a.repr) ++ ")"
    | (kBool.validFXTail a) => "validFXTail(" ++ (a.repr) ++ ")"
    | (kBool.allFormats a) => "allFormats(" ++ (a.repr) ++ ")"
    | (kBool.required a₀ a₁) => "required(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.requiredNumeric a₀ a₁ a₂) => "requiredNumeric(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kBool.requiredPlain a₀ a₁ a₂) => "requiredPlain(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kBool.minmaxName a) => "minmaxName(" ++ (reprStr a) ++ ")"
    | (kBool.compareName a) => "compareName(" ++ (reprStr a) ++ ")"
    | (kBool.predicateName a) => "predicateName(" ++ (reprStr a) ++ ")"
    | (kBool.formatNameOp a) => "formatNameOp(" ++ (reprStr a) ++ ")"
    | (kBool.numericPlainName a) => "numericPlainName(" ++ (reprStr a) ++ ")"
    | (kBool.blockElementArity a₀ a₁) => "blockElementArity(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.numericResult a) => "numericResult(" ++ (a.repr) ++ ")"
    | (kBool.hasDeclaration a₀ a₁) => "hasDeclaration(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.declarationsCover a₀ a₁) => "declarationsCover(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.partition a₀ a₁) => "partition(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.partitionDisjoint a) => "partitionDisjoint(" ++ (a.repr) ++ ")"
    | (kBool.validSpecialization a) => "validSpecialization(" ++ (a.repr) ++ ")"
    | (kBool.numericArity a₀ a₁) => "numericArity(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.plainArity a₀ a₁) => "plainArity(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.wellFormedDeclaration a) => "wellFormedDeclaration(" ++ (a.repr) ++ ")"
    | (kBool.evidenceComplete a) => "evidenceComplete(" ++ (a.repr) ++ ")"
    | (kBool.memberCode a₀ a₁) => "memberCode(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.disjointCodes a₀ a₁) => "disjointCodes(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.uniqueCodes a) => "uniqueCodes(" ++ (a.repr) ++ ")"
    | (kBool.subsetCodes a₀ a₁) => "subsetCodes(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.partition2 a₀ a₁ a₂) => "partition2(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kBool.inArityTable a₀ a₁ a₂) => "inArityTable(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ", " ++ (a₂.repr) ++ ")"
    | (kBool.TotalOrder a₀ a₁ a₂ a₃) => "TotalOrder(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (reprStr a₂) ++ ", " ++ (reprStr a₃) ++ ")"
    | (kBool.eqeq₀ a₀ a₁) => "_==_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.ifthenelsefi a₀ a₁ a₂) => "if_then_else_fi(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kBool.eqeq₁ a₀ a₁) => "_==_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.eqeq₂ a₀ a₁) => "_==_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.eqslasheq₀ a₀ a₁) => "_=/=_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.eqeq₃ a₀ a₁) => "_==_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.eqeq₄ a₀ a₁) => "_==_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.eqeq₅ a₀ a₁) => "_==_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.eqeq₆ a₀ a₁) => "_==_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.eqeq₇ a₀ a₁) => "_==_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.eqslasheq₁ a₀ a₁) => "_=/=_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kBool.eqslasheq₂ a₀ a₁) => "_=/=_(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kBool.eqeq₈ a₀ a₁) => "_==_(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"

  def kCodeSeq.repr : kCodeSeq → String
    | kCodeSeq.cnil => "cnil"
    | (kCodeSeq.ccons a₀ a₁) => "ccons(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ")"
    | (kCodeSeq.blockProject a₀ a₁ a₂ a₃ a₄ a₅) => "blockProject(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (reprStr a₄) ++ ", " ++ (a₅.repr) ++ ")"
    | (kCodeSeq.projectElements a₀ a₁ a₂ a₃ a₄) => "projectElements(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (reprStr a₄) ++ ")"
    | (kCodeSeq.projectUnscaled a₀ a₁ a₂ a₃) => "projectUnscaled(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (reprStr a₃) ++ ")"
    | (kCodeSeq.«at» a₀ a₁) => "at(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kCodeSeq.partitionUnion a) => "partitionUnion(" ++ (a.repr) ++ ")"
    | (kCodeSeq.appendCodes a₀ a₁) => "appendCodes(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kCodeSeq.ConvertFromBlock a₀ a₁ a₂ a₃ a₄ a₅ a₆) => "ConvertFromBlock(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (reprStr a₅) ++ ", " ++ (a₆.repr) ++ ")"
    | (kCodeSeq.ConvertToBlock a₀ a₁ a₂ a₃ a₄ a₅ a₆) => "ConvertToBlock(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (reprStr a₆) ++ ")"

  def kDeclaration.repr : kDeclaration → String
    | (kDeclaration.exact a₀ a₁ a₂) => "exact(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ", " ++ (a₂.repr) ++ ")"
    | (kDeclaration.approximate a₀ a₁ a₂ a₃) => "approximate(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ")"
    | (kDeclaration.«at» a₀ a₁) => "at(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kDeclaration.partitioned a₀ a₁ a₂ a₃ a₄) => "partitioned(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ")"

  def kDeclarationSeq.repr : kDeclarationSeq → String
    | kDeclarationSeq.dnil => "dnil"
    | (kDeclarationSeq.dcons a₀ a₁) => "dcons(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"

  def kDomain.repr : kDomain → String
    | kDomain.Finite => "Finite"
    | kDomain.Extended => "Extended"
    | (kDomain.DomainOf a) => "DomainOf(" ++ (a.repr) ++ ")"

  def kFormat.repr : kFormat → String
    | (kFormat.Binary a₀ a₁ a₂ a₃) => "Binary(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ")"
    | kFormat.binary64 => "binary64"
    | kFormat.binary32 => "binary32"
    | kFormat.binary16 => "binary16"
    | kFormat.BFloat16 => "BFloat16"
    | (kFormat.«at» a₀ a₁) => "at(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"

  def kFormatSeq.repr : kFormatSeq → String
    | kFormatSeq.fnil => "fnil"
    | (kFormatSeq.fcons a₀ a₁) => "fcons(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"

  def kKappa.repr : kKappa → String
    | (kKappa.steps a) => "steps(" ++ (reprStr a) ++ ")"
    | kKappa.kNaN => "kNaN"
    | kKappa.kInfinity => "kInfinity"
    | (kKappa.partBound a) => "partBound(" ++ (a.repr) ++ ")"
    | (kKappa.declarationKappa a) => "declarationKappa(" ++ (a.repr) ++ ")"
    | (kKappa.observationKappa a) => "observationKappa(" ++ (a.repr) ++ ")"
    | (kKappa.batchKappa a) => "batchKappa(" ++ (a.repr) ++ ")"
    | (kKappa.mergeKappa a₀ a₁) => "mergeKappa(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"

  def kKappaPart.repr : kKappaPart → String
    | (kKappaPart.kappaPart a₀ a₁) => "kappaPart(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kKappaPart.«at» a₀ a₁) => "at(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"

  def kKappaPartSeq.repr : kKappaPartSeq → String
    | kKappaPartSeq.knil => "knil"
    | (kKappaPartSeq.kcons a₀ a₁) => "kcons(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"

  def kObservation.repr : kObservation → String
    | (kObservation.observation a₀ a₁ a₂ a₃ a₄) => "observation(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (reprStr a₃) ++ ", " ++ (reprStr a₄) ++ ")"
    | (kObservation.«at» a₀ a₁) => "at(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"

  def kObservationSeq.repr : kObservationSeq → String
    | kObservationSeq.onil => "onil"
    | (kObservationSeq.ocons a₀ a₁) => "ocons(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"

  def kPartitionSeq.repr : kPartitionSeq → String
    | kPartitionSeq.pnil => "pnil"
    | (kPartitionSeq.pcons a₀ a₁) => "pcons(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kPartitionSeq.partRegions a) => "partRegions(" ++ (a.repr) ++ ")"

  def kProjSpec.repr : kProjSpec → String
    | (kProjSpec.proj a₀ a₁) => "proj(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kProjSpec.projectionAt a₀ a₁) => "projectionAt(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"

  def kRandomSeq.repr : kRandomSeq → String
    | kRandomSeq.rnil => "rnil"
    | (kRandomSeq.rcons a₀ a₁) => "rcons(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ")"

  def kSatMode.repr : kSatMode → String
    | kSatMode.SatNone => "SatNone"
    | kSatMode.SatFinite => "SatFinite"
    | kSatMode.SatPropagate => "SatPropagate"
    | (kSatMode.SatOf a) => "SatOf(" ++ (a.repr) ++ ")"

  def kSignedness.repr : kSignedness → String
    | kSignedness.Signed => "Signed"
    | kSignedness.Unsigned => "Unsigned"
    | (kSignedness.SignednessOf a) => "SignednessOf(" ++ (a.repr) ++ ")"

  def kSpecialization.repr : kSpecialization → String
    | (kSpecialization.numeric a₀ a₁ a₂) => "numeric(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kSpecialization.plain a₀ a₁) => "plain(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ")"
    | (kSpecialization.blockElements a₀ a₁ a₂ a₃) => "blockElements(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ")"
    | (kSpecialization.blockReduction a₀ a₁ a₂ a₃) => "blockReduction(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ")"
    | (kSpecialization.blockScale a₀ a₁ a₂ a₃ a₄) => "blockScale(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ")"
    | (kSpecialization.«at» a₀ a₁) => "at(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kSpecialization.declaredIdentity a) => "declaredIdentity(" ++ (a.repr) ++ ")"

  def kSpecializationSeq.repr : kSpecializationSeq → String
    | kSpecializationSeq.snil => "snil"
    | (kSpecializationSeq.scons a₀ a₁) => "scons(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"

  def kXReal.repr : kXReal → String
    | (kXReal.fin a) => "fin(" ++ (reprStr a) ++ ")"
    | kXReal.posInf => "posInf"
    | kXReal.negInf => "negInf"
    | kXReal.nan => "nan"
    | (kXReal.externalDecode a₀ a₁) => "externalDecode(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kXReal.decode a₀ a₁) => "decode(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kXReal.roundToPrecision a₀ a₁ a₂ a₃) => "roundToPrecision(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ")"
    | (kXReal.saturate a₀ a₁ a₂ a₃ a₄ a₅ a₆) => "saturate(" ++ (reprStr a₀) ++ ", " ++ (reprStr a₁) ++ ", " ++ (a₂.repr) ++ ", " ++ (a₃.repr) ++ ", " ++ (a₄.repr) ++ ", " ++ (a₅.repr) ++ ", " ++ (a₆.repr) ++ ")"
    | (kXReal.overflow a₀ a₁ a₂) => "overflow(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kXReal.omegaConvert a) => "omegaConvert(" ++ (a.repr) ++ ")"
    | (kXReal.omegaAbs a) => "omegaAbs(" ++ (a.repr) ++ ")"
    | (kXReal.omegaNegate a) => "omegaNegate(" ++ (a.repr) ++ ")"
    | (kXReal.omegaRecip a) => "omegaRecip(" ++ (a.repr) ++ ")"
    | (kXReal.omegaCopySign a₀ a₁) => "omegaCopySign(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaAdd a₀ a₁) => "omegaAdd(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaSubtract a₀ a₁) => "omegaSubtract(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMultiply a₀ a₁) => "omegaMultiply(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaDivide a₀ a₁) => "omegaDivide(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaFMA a₀ a₁ a₂) => "omegaFMA(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kXReal.omegaFAA a₀ a₁ a₂) => "omegaFAA(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kXReal.«at» a₀ a₁) => "at(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
    | (kXReal.normalizeElement a₀ a₁) => "normalizeElement(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMinimum a₀ a₁) => "omegaMinimum(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMaximum a₀ a₁) => "omegaMaximum(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMinimumNumber a₀ a₁) => "omegaMinimumNumber(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMaximumNumber a₀ a₁) => "omegaMaximumNumber(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMinimumMagnitude a₀ a₁) => "omegaMinimumMagnitude(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMaximumMagnitude a₀ a₁) => "omegaMaximumMagnitude(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMinimumMagnitudeNumber a₀ a₁) => "omegaMinimumMagnitudeNumber(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMaximumMagnitudeNumber a₀ a₁) => "omegaMaximumMagnitudeNumber(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMinimumFinite a₀ a₁) => "omegaMinimumFinite(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaMaximumFinite a₀ a₁) => "omegaMaximumFinite(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaClamp a₀ a₁ a₂) => "omegaClamp(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kXReal.foldAdd a₀ a₁) => "foldAdd(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.foldMultiply a₀ a₁) => "foldMultiply(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.foldMaximumFinite a₀ a₁) => "foldMaximumFinite(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.realAdd a₀ a₁) => "realAdd(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.realMultiply a₀ a₁) => "realMultiply(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.realNegate a) => "realNegate(" ++ (a.repr) ++ ")"
    | (kXReal.realAbs a) => "realAbs(" ++ (a.repr) ++ ")"
    | (kXReal.realDivide a₀ a₁) => "realDivide(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.piMultiple a) => "piMultiple(" ++ (reprStr a) ++ ")"
    | kXReal.pi => "pi"
    | (kXReal.omegaHypot a₀ a₁) => "omegaHypot(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaArcTan2 a₀ a₁) => "omegaArcTan2(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaArcTan2Pi a₀ a₁) => "omegaArcTan2Pi(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXReal.omegaSqrt a) => "omegaSqrt(" ++ (a.repr) ++ ")"
    | (kXReal.omegaRSqrt a) => "omegaRSqrt(" ++ (a.repr) ++ ")"
    | (kXReal.omegaExp a) => "omegaExp(" ++ (a.repr) ++ ")"
    | (kXReal.omegaExp2 a) => "omegaExp2(" ++ (a.repr) ++ ")"
    | (kXReal.omegaLog a) => "omegaLog(" ++ (a.repr) ++ ")"
    | (kXReal.omegaLog2 a) => "omegaLog2(" ++ (a.repr) ++ ")"
    | (kXReal.omegaLogOnePlus a) => "omegaLogOnePlus(" ++ (a.repr) ++ ")"
    | (kXReal.omegaExpMinusOne a) => "omegaExpMinusOne(" ++ (a.repr) ++ ")"
    | (kXReal.omegaSin a) => "omegaSin(" ++ (a.repr) ++ ")"
    | (kXReal.omegaCos a) => "omegaCos(" ++ (a.repr) ++ ")"
    | (kXReal.omegaTan a) => "omegaTan(" ++ (a.repr) ++ ")"
    | (kXReal.omegaArcSin a) => "omegaArcSin(" ++ (a.repr) ++ ")"
    | (kXReal.omegaArcCos a) => "omegaArcCos(" ++ (a.repr) ++ ")"
    | (kXReal.omegaArcTan a) => "omegaArcTan(" ++ (a.repr) ++ ")"
    | (kXReal.omegaSinh a) => "omegaSinh(" ++ (a.repr) ++ ")"
    | (kXReal.omegaCosh a) => "omegaCosh(" ++ (a.repr) ++ ")"
    | (kXReal.omegaTanh a) => "omegaTanh(" ++ (a.repr) ++ ")"
    | (kXReal.omegaArcSinh a) => "omegaArcSinh(" ++ (a.repr) ++ ")"
    | (kXReal.omegaArcCosh a) => "omegaArcCosh(" ++ (a.repr) ++ ")"
    | (kXReal.omegaArcTanh a) => "omegaArcTanh(" ++ (a.repr) ++ ")"
    | (kXReal.omegaSinPi a) => "omegaSinPi(" ++ (a.repr) ++ ")"
    | (kXReal.omegaCosPi a) => "omegaCosPi(" ++ (a.repr) ++ ")"
    | (kXReal.omegaTanPi a) => "omegaTanPi(" ++ (a.repr) ++ ")"
    | (kXReal.omegaArcSinPi a) => "omegaArcSinPi(" ++ (a.repr) ++ ")"
    | (kXReal.omegaArcCosPi a) => "omegaArcCosPi(" ++ (a.repr) ++ ")"
    | (kXReal.omegaArcTanPi a) => "omegaArcTanPi(" ++ (a.repr) ++ ")"
    | (kXReal.omegaSoftplus a) => "omegaSoftplus(" ++ (a.repr) ++ ")"
    | (kXReal.exprSqrt a) => "exprSqrt(" ++ (a.repr) ++ ")"
    | (kXReal.exprExp a) => "exprExp(" ++ (a.repr) ++ ")"
    | (kXReal.exprExp2 a) => "exprExp2(" ++ (a.repr) ++ ")"
    | (kXReal.exprLog a) => "exprLog(" ++ (a.repr) ++ ")"
    | (kXReal.exprLog2 a) => "exprLog2(" ++ (a.repr) ++ ")"
    | (kXReal.exprSin a) => "exprSin(" ++ (a.repr) ++ ")"
    | (kXReal.exprCos a) => "exprCos(" ++ (a.repr) ++ ")"
    | (kXReal.exprTan a) => "exprTan(" ++ (a.repr) ++ ")"
    | (kXReal.exprArcSin a) => "exprArcSin(" ++ (a.repr) ++ ")"
    | (kXReal.exprArcCos a) => "exprArcCos(" ++ (a.repr) ++ ")"
    | (kXReal.exprArcTan a) => "exprArcTan(" ++ (a.repr) ++ ")"
    | (kXReal.exprSinh a) => "exprSinh(" ++ (a.repr) ++ ")"
    | (kXReal.exprCosh a) => "exprCosh(" ++ (a.repr) ++ ")"
    | (kXReal.exprTanh a) => "exprTanh(" ++ (a.repr) ++ ")"
    | (kXReal.exprArcSinh a) => "exprArcSinh(" ++ (a.repr) ++ ")"
    | (kXReal.exprArcCosh a) => "exprArcCosh(" ++ (a.repr) ++ ")"
    | (kXReal.exprArcTanh a) => "exprArcTanh(" ++ (a.repr) ++ ")"
    | (kXReal.ifthenelsefi a₀ a₁ a₂) => "if_then_else_fi(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"

  def kXSeq.repr : kXSeq → String
    | kXSeq.xnil => "xnil"
    | (kXSeq.xcons a₀ a₁) => "xcons(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.decodeElements a₀ a₁) => "decodeElements(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.multiplyElements a₀ a₁) => "multiplyElements(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.blockDecode a₀ a₁ a₂ a₃ a₄) => "blockDecode(" ++ (reprStr a₀) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ", " ++ (reprStr a₃) ++ ", " ++ (a₄.repr) ++ ")"
    | (kXSeq.absElements a) => "absElements(" ++ (a.repr) ++ ")"
    | (kXSeq.pairProducts a₀ a₁) => "pairProducts(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapConvert a) => "mapConvert(" ++ (a.repr) ++ ")"
    | (kXSeq.mapAbs a) => "mapAbs(" ++ (a.repr) ++ ")"
    | (kXSeq.mapNegate a) => "mapNegate(" ++ (a.repr) ++ ")"
    | (kXSeq.mapCopySign a₀ a₁) => "mapCopySign(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapAdd a₀ a₁) => "mapAdd(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapSubtract a₀ a₁) => "mapSubtract(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapMultiply a₀ a₁) => "mapMultiply(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapDivide a₀ a₁) => "mapDivide(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapFMA a₀ a₁ a₂) => "mapFMA(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kXSeq.mapFAA a₀ a₁ a₂) => "mapFAA(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kXSeq.mapRecip a) => "mapRecip(" ++ (a.repr) ++ ")"
    | (kXSeq.mapMinimum a₀ a₁) => "mapMinimum(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapMaximum a₀ a₁) => "mapMaximum(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapMinimumNumber a₀ a₁) => "mapMinimumNumber(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapMaximumNumber a₀ a₁) => "mapMaximumNumber(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapMinimumMagnitude a₀ a₁) => "mapMinimumMagnitude(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapMaximumMagnitude a₀ a₁) => "mapMaximumMagnitude(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapMinimumMagnitudeNumber a₀ a₁) => "mapMinimumMagnitudeNumber(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapMaximumMagnitudeNumber a₀ a₁) => "mapMaximumMagnitudeNumber(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapMinimumFinite a₀ a₁) => "mapMinimumFinite(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapMaximumFinite a₀ a₁) => "mapMaximumFinite(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapClamp a₀ a₁ a₂) => "mapClamp(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"
    | (kXSeq.mapSqrt a) => "mapSqrt(" ++ (a.repr) ++ ")"
    | (kXSeq.mapRSqrt a) => "mapRSqrt(" ++ (a.repr) ++ ")"
    | (kXSeq.mapExp a) => "mapExp(" ++ (a.repr) ++ ")"
    | (kXSeq.mapExp2 a) => "mapExp2(" ++ (a.repr) ++ ")"
    | (kXSeq.mapLog a) => "mapLog(" ++ (a.repr) ++ ")"
    | (kXSeq.mapLog2 a) => "mapLog2(" ++ (a.repr) ++ ")"
    | (kXSeq.mapLogOnePlus a) => "mapLogOnePlus(" ++ (a.repr) ++ ")"
    | (kXSeq.mapExpMinusOne a) => "mapExpMinusOne(" ++ (a.repr) ++ ")"
    | (kXSeq.mapSin a) => "mapSin(" ++ (a.repr) ++ ")"
    | (kXSeq.mapCos a) => "mapCos(" ++ (a.repr) ++ ")"
    | (kXSeq.mapTan a) => "mapTan(" ++ (a.repr) ++ ")"
    | (kXSeq.mapArcSin a) => "mapArcSin(" ++ (a.repr) ++ ")"
    | (kXSeq.mapArcCos a) => "mapArcCos(" ++ (a.repr) ++ ")"
    | (kXSeq.mapArcTan a) => "mapArcTan(" ++ (a.repr) ++ ")"
    | (kXSeq.mapSinh a) => "mapSinh(" ++ (a.repr) ++ ")"
    | (kXSeq.mapCosh a) => "mapCosh(" ++ (a.repr) ++ ")"
    | (kXSeq.mapTanh a) => "mapTanh(" ++ (a.repr) ++ ")"
    | (kXSeq.mapArcSinh a) => "mapArcSinh(" ++ (a.repr) ++ ")"
    | (kXSeq.mapArcCosh a) => "mapArcCosh(" ++ (a.repr) ++ ")"
    | (kXSeq.mapArcTanh a) => "mapArcTanh(" ++ (a.repr) ++ ")"
    | (kXSeq.mapSinPi a) => "mapSinPi(" ++ (a.repr) ++ ")"
    | (kXSeq.mapCosPi a) => "mapCosPi(" ++ (a.repr) ++ ")"
    | (kXSeq.mapTanPi a) => "mapTanPi(" ++ (a.repr) ++ ")"
    | (kXSeq.mapArcSinPi a) => "mapArcSinPi(" ++ (a.repr) ++ ")"
    | (kXSeq.mapArcCosPi a) => "mapArcCosPi(" ++ (a.repr) ++ ")"
    | (kXSeq.mapArcTanPi a) => "mapArcTanPi(" ++ (a.repr) ++ ")"
    | (kXSeq.mapSoftplus a) => "mapSoftplus(" ++ (a.repr) ++ ")"
    | (kXSeq.mapHypot a₀ a₁) => "mapHypot(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapArcTan2 a₀ a₁) => "mapArcTan2(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
    | (kXSeq.mapArcTan2Pi a₀ a₁) => "mapArcTan2Pi(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ")"
end

def kClassEnum.repr : kClassEnum → String
  | kClassEnum.ClsNaN => "ClsNaN"
  | kClassEnum.ClsNegativeInfinity => "ClsNegativeInfinity"
  | kClassEnum.ClsNegativeNormal => "ClsNegativeNormal"
  | kClassEnum.ClsNegativeSubnormal => "ClsNegativeSubnormal"
  | kClassEnum.ClsZero => "ClsZero"
  | kClassEnum.ClsPositiveSubnormal => "ClsPositiveSubnormal"
  | kClassEnum.ClsPositiveNormal => "ClsPositiveNormal"
  | kClassEnum.ClsPositiveInfinity => "ClsPositiveInfinity"
  | (kClassEnum.Class a₀ a₁) => "Class(" ++ (a₀.repr) ++ ", " ++ (reprStr a₁) ++ ")"
  | (kClassEnum.ifthenelsefi a₀ a₁ a₂) => "if_then_else_fi(" ++ (a₀.repr) ++ ", " ++ (a₁.repr) ++ ", " ++ (a₂.repr) ++ ")"

instance : Repr kBool := ⟨ λ x _ => Std.Format.text (kBool.repr x) ⟩
instance : Repr kXReal := ⟨ λ x _ => Std.Format.text (kXReal.repr x) ⟩
instance : Repr kSignedness := ⟨ λ x _ => Std.Format.text (kSignedness.repr x) ⟩
instance : Repr kDomain := ⟨ λ x _ => Std.Format.text (kDomain.repr x) ⟩
instance : Repr kFormat := ⟨ λ x _ => Std.Format.text (kFormat.repr x) ⟩
instance : Repr kBoundQuery := ⟨ λ x _ => Std.Format.text (kBoundQuery.repr x) ⟩
instance : Repr kRandomSeq := ⟨ λ x _ => Std.Format.text (kRandomSeq.repr x) ⟩
instance : Repr kBlockRoundMode := ⟨ λ x _ => Std.Format.text (kBlockRoundMode.repr x) ⟩
instance : Repr kSatMode := ⟨ λ x _ => Std.Format.text (kSatMode.repr x) ⟩
instance : Repr kProjSpec := ⟨ λ x _ => Std.Format.text (kProjSpec.repr x) ⟩
instance : Repr kBlockProjSpec := ⟨ λ x _ => Std.Format.text (kBlockProjSpec.repr x) ⟩
instance : Repr kXSeq := ⟨ λ x _ => Std.Format.text (kXSeq.repr x) ⟩
instance : Repr kCodeSeq := ⟨ λ x _ => Std.Format.text (kCodeSeq.repr x) ⟩
instance : Repr kBlock := ⟨ λ x _ => Std.Format.text (kBlock.repr x) ⟩
instance : Repr kFormatSeq := ⟨ λ x _ => Std.Format.text (kFormatSeq.repr x) ⟩
instance : Repr kArityEntry := ⟨ λ x _ => Std.Format.text (kArityEntry.repr x) ⟩
instance : Repr kSpecialization := ⟨ λ x _ => Std.Format.text (kSpecialization.repr x) ⟩
instance : Repr kKappa := ⟨ λ x _ => Std.Format.text (kKappa.repr x) ⟩
instance : Repr kKappaPart := ⟨ λ x _ => Std.Format.text (kKappaPart.repr x) ⟩
instance : Repr kObservation := ⟨ λ x _ => Std.Format.text (kObservation.repr x) ⟩
instance : Repr kEvidence := ⟨ λ x _ => Std.Format.text (kEvidence.repr x) ⟩
instance : Repr kDeclaration := ⟨ λ x _ => Std.Format.text (kDeclaration.repr x) ⟩
instance : Repr kKappaPartSeq := ⟨ λ x _ => Std.Format.text (kKappaPartSeq.repr x) ⟩
instance : Repr kPartitionSeq := ⟨ λ x _ => Std.Format.text (kPartitionSeq.repr x) ⟩
instance : Repr kDeclarationSeq := ⟨ λ x _ => Std.Format.text (kDeclarationSeq.repr x) ⟩
instance : Repr kSpecializationSeq := ⟨ λ x _ => Std.Format.text (kSpecializationSeq.repr x) ⟩
instance : Repr kClassEnum := ⟨ λ x _ => Std.Format.text (kClassEnum.repr x) ⟩
instance : Repr kObservationSeq := ⟨ λ x _ => Std.Format.text (kObservationSeq.repr x) ⟩
instance : Repr kArityTable := ⟨ λ x _ => Std.Format.text (kArityTable.repr x) ⟩

end Maude
