#!/usr/bin/env python3
"""Generate scalar/block/scaled schemas and conformance arity tables."""
import argparse,json,pathlib,re,sys
sys.dont_write_bytecode = True
from maude_source import format_equations
ROOT=pathlib.Path(__file__).resolve().parents[1]

TABLES = {
    'numericArityTable': ('p3109-decl-numeric-table', 'clause=4.3; page=19-20; clause=5.8; page=70'),
    'plainArityTable': ('p3109-decl-plain-table', 'clause=4.3; page=19-20'),
    'blockElementArityTable': ('p3109-block-element-arity-table', 'clause=5.5.1-5.5.2; page=64-65; clause=5.7; page=69'),
}


def arity_entries(operations):
    """Count format parameters, adding scale formats for derived operations."""
    tables = {name: [] for name in TABLES}
    for operation in operations:
        name = operation['name']
        parameters = operation['parameters']
        formats = sum(parameter.startswith('f') for parameter in parameters)
        if 'B' in parameters:
            # Reductions and scale-producing operations have separate schemas.
            if operation['result'] == 'codes':
                tables['blockElementArityTable'].append((name, formats))
        elif 'rho' in parameters:
            tables['numericArityTable'].append((name, formats))
            if operation['scaled']:
                tables['numericArityTable'].append(('Scaled' + name, formats + operation['arity']))
            if operation['block']:
                tables['blockElementArityTable'].append(('Block' + name, formats + operation['arity'] + 1))
        else:
            tables['plainArityTable'].append((name, formats))
    # Preserve the original table order: arity, base before scaled, inventory order.
    for entries in tables.values():
        entries.sort(key=lambda entry: (entry[1], entry[0].startswith('Scaled')))
    return tables


def generate_tables(source, operations):
    """Replace only the marked table equations in the handwritten module."""
    for name, entries in arity_entries(operations).items():
        label, metadata = TABLES[name]
        term = 'anil'
        for operation, arity in reversed(entries):
            term = f'acons(entry({json.dumps(operation)}, {arity}), {term})'
        equation = format_equations(f'  eq [{label}] : {name} = {term} [metadata "{metadata}"] .')
        pattern = rf'(  --- BEGIN GENERATED {name}\n).*?(\n  --- END GENERATED {name})'
        source, count = re.subn(pattern, lambda match: match[1] + equation + match[2], source, flags=re.S)
        if count != 1:
            raise ValueError('Expected one generated region for ' + name)
    return source

def generate(profile, block):
    operations = json.loads((ROOT / 'inventory/operations.json').read_text())['operations']
    operations = [o for o in operations if o.get('wrapper') and o['profile'] == profile
                  and o['result'] == 'code' and (not block or o['block'])]
    mod = 'P3109-' + ('SYMBOLIC-' if profile == 'symbolic' else '')
    mod += 'BLOCK-WRAPPERS' if block else 'SCALAR'
    target = 'P3109-OMEGA-ELEMENTARY' if profile == 'symbolic' else 'P3109-OMEGA-EXTREMA'
    out = ['--- Generated by tools/generate-wrappers.py; edit inventory or generator.']
    # Both scalar and block instances use these views, loaded with the scalar profile.
    if not block:
        for o in operations:
            out += [f'view {o["name"]}Kernel from P3109-KERNEL{o["arity"]} to {target} is',
                    f'  op kernel to omega{o["name"]} .', 'endv']
    out += [f'fmod {mod} is']
    deps = ['P3109-BLOCK'] if block else ['P3109-PROJECT', 'P3109-OMEGA-EXTREMA']
    if profile == 'symbolic':
        deps += ['P3109-OMEGA-ELEMENTARY']
    out += ['  including ' + dep + ' .' for dep in deps]
    for o in operations:
        name, n = o['name'], o['arity']
        if n not in (1, 2, 3):
            raise ValueError(f'Unsupported wrapper arity: {name}/{n}')
        if block:
            renames = [f'op elementwise to Block{name}, op scaled to Scaled{name}, op mapped to map{name}',
                       f'label p3109-template-block-{n} to p3109-block-{name}',
                       f'label p3109-template-map-{n}-nil to p3109-map-{name}-nil',
                       f'label p3109-template-map-{n}-cons to p3109-map-{name}-cons',
                       f'label p3109-template-scaled-{n} to p3109-scaled-{name}']
        else:
            renames = [f'op scalar to {name}',
                       f'label p3109-template-scalar-{n} to p3109-scalar-{name}']
        template = 'BLOCK' if block else 'SCALAR'
        out += [f'  including P3109-{template}-TEMPLATE{n}' + '{' + name + 'Kernel} * (',
                '    ' + ',\n    '.join(renames) + ') .']
    return '\n'.join(out + ['endfm', ''])

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');a=p.parse_args()
    bad=[]
    for profile in ['core','symbolic']:
        for block in [False,True]:
            path=ROOT/('lib' if profile=='core' else 'symbolic')/('block-wrappers.maude' if block else 'scalar-ops.maude')
            text=generate(profile,block)
            if a.check:
                if not path.exists() or path.read_text()!=text:bad.append(str(path))
            else:path.write_text(text)
    path=ROOT/'lib/conformance.maude'
    operations=json.loads((ROOT/'inventory/operations.json').read_text())['operations']
    text=generate_tables(path.read_text(),operations)
    if a.check:
        if path.read_text()!=text:bad.append(str(path))
    else:path.write_text(text)
    if bad:sys.exit('Stale generated files: '+', '.join(bad))
    print('Wrappers and arity tables verified.' if a.check else 'Wrappers and arity tables generated.')
if __name__=='__main__':main()
