using AIFloats
using Documenter
using Documenter: Remotes

DocMeta.setdocmeta!(AIFloats, :DocTestSetup, :(using AIFloats); recursive = true)

# ---- the page tree ----------------------------------------------------------
# EXPLICIT, not discovered by walking `src/`. Two reasons, both learned the hard
# way (docs/refinedocs2.md P2-7):
#
#   * navigation order and titles are reviewable in one place, and nesting
#     deeper than one directory does not need the recursion to be right;
#   * a planning document dropped into `docs/` cannot become a published page
#     by accident. Adding a page is one line here, on purpose.

const PAGES = [
    "index.md",
    "10-getting-started.md",
    "20-concepts.md",
    "30-formats.md",
    "40-projections.md",
    "Operations" => "45-operations.md",
    "Examples" => [
        "Basic examples" => "70-examples/10-basic.md",
        "Intermediate examples" => "70-examples/20-intermediate.md",
        "Advanced examples" => "70-examples/30-advanced.md",
        "Technical examples" => "70-examples/40-technical.md",
    ],
    "60-benchmarks.md",
    "Reference" => [
        # The landing page's own H1 stays "Reference"; in the menu it sits
        # under a group of that name, where "Reference > Reference" reads as a
        # mistake rather than a hierarchy.
        "Overview" => "95-reference.md",
        "95-reference/10-core.md",
        "95-reference/20-operations.md",
        "95-reference/30-blocks.md",
        "95-reference/40-governance.md",
    ],
    # The deep material, last: how the results are obtained, then everything
    # about how they are obtained here. Mechanism rather than interface, and a
    # reader reaches it after the pages that state the contracts.
    "Algorithms" => "96-algorithms.md",
    "Internals" => [
        "Implementation" => "50-status.md",
        "Dyadic Numbers" => "97-internals.md",
        "Fused Ops" => [
            "FMA" => "98-fma128.md",
            "FAA" => "99-faa128.md",
        ],
    ],
    "For developers" => [
        "Contributing" => "90-contributing.md",
        "Developing" => "91-developer.md",
    ],
]

# Every page named above must exist, and every page in `src/` must be named
# above. A missing file is a broken link; an unlisted file is either a page
# nobody can reach or a planning document that should not be in `src/`.
function check_page_tree()
    listed = String[]
    walk(x::String) = push!(listed, x)
    walk(x::Pair) = walk(x.second)
    walk(x::Vector) = foreach(walk, x)
    foreach(walk, PAGES)

    src = joinpath(@__DIR__, "src")
    found = String[]
    for (root, _, files) in walkdir(src), f in files
        endswith(f, ".md") && push!(found, relpath(joinpath(root, f), src))
    end

    missing_files = setdiff(listed, found)
    isempty(missing_files) || error("PAGES names files that do not exist: $missing_files")
    unlisted = setdiff(found, listed)
    isempty(unlisted) || error(
        "docs/src holds pages that PAGES does not list: $unlisted\n" *
        "Add them to PAGES in docs/make.jl, or move them out of docs/src.")
    return nothing
end

# ---- benchmark page ---------------------------------------------------------
# The results page is GENERATED at docs-build time by running the suite in its
# own project, as a subprocess. A subprocess and not an `include` because
# Chairmarks belongs to benchmark/Project.toml and must not become a dependency
# of the docs (or of the package) — the same isolation the suite itself keeps.
#
# Set AIFLOATS_DOCS_BENCHMARKS=0 to skip the run. The last generated page is
# then LEFT IN PLACE rather than overwritten with a placeholder: a docs build
# with benchmarks off must not silently destroy the measurements a previous
# build produced (docs/refinedocs2.md V-2). A failed run still never fails the
# build — the numbers are informative, the prose around them is the
# documentation.

const BENCH_PAGE = joinpath(@__DIR__, "src", "60-benchmarks.md")

function run_benchmarks()
    root = dirname(@__DIR__)
    proj = joinpath(root, "benchmark")
    script = joinpath(proj, "runbenchmarks.jl")
    # Fixed at 4 unless overridden, not `auto`: the threading rows exist to be
    # compared against each other and against THREAD_MIN_ELEMS, which was refit
    # at four threads. A machine-dependent thread count would make two builds
    # incomparable for the one thing those rows are for.
    nthreads = get(ENV, "JULIA_NUM_THREADS", "4")
    run(`$(Base.julia_cmd()) --project=$proj --startup-file=no -e
         "import Pkg; Pkg.instantiate()"`)
    read(`$(Base.julia_cmd()) --project=$proj --startup-file=no -t $nthreads $script`, String)
end

const BENCH_HEADER = """
# [Benchmark results](@id benchmarks)

Generated by running `benchmark/runbenchmarks.jl` during a documentation
build. Nothing here is hand-entered.

**These numbers describe the machine that built this page**, recorded in the
header below along with the commit and the thread count. A shared CI runner
is noisy and its absolute times mean little; the *ratios* between rows on one
run are the informative part. Reproduce locally with:

```
julia --project=benchmark -t 4 benchmark/runbenchmarks.jl          # all suites
julia --project=benchmark -t 4 benchmark/runbenchmarks.jl scalar   # one suite
```

The suite is run with four threads unless `JULIA_NUM_THREADS` says
otherwise, whatever the machine's core count, so that the threading rows
stay comparable between builds.

What the columns mean: time per call, then allocations and bytes when a call
allocates at all (their absence is itself the claim — most scalar rows are
allocation-free), and elements per second for array rows. The `latency`
suite measures package load and first-call compilation in *fresh processes*,
because those happen exactly once and cannot be sampled.

**Check the commit in the header below.** These rows describe the tree that was
measured, which is not necessarily the tree you are reading about. A row marked
`(dirty)`, or naming a commit older than the current one, is historical
evidence — see [Performance characteristics](@ref performance) for the design
decisions these measurements justify, and re-run the suite from a clean commit
before quoting a number anywhere else.

"""

function write_benchmark_page()
    if get(ENV, "AIFLOATS_DOCS_BENCHMARKS", "1") in ("0", "false", "no")
        if isfile(BENCH_PAGE)
            @info "AIFLOATS_DOCS_BENCHMARKS=0: keeping the existing benchmark page"
            return nothing
        end
        write(BENCH_PAGE, BENCH_HEADER *
              "!!! note \"Not run\"\n    " *
              "This build set `AIFLOATS_DOCS_BENCHMARKS=0`, and no previously " *
              "generated page was present, so this page holds no measurements.\n")
        return nothing
    end
    body = try
        "```\n" * run_benchmarks() * "```\n"
    catch err
        @warn "benchmark suite did not run; the page will say so" exception = err
        "!!! warning \"Benchmarks did not run\"\n    " *
        "The suite failed to run during this build. See `benchmark/` to run it " *
        "locally.\n"
    end
    write(BENCH_PAGE, BENCH_HEADER * body)
    return nothing
end

# ---- reference page ---------------------------------------------------------
# GENERATED, for the same reason the benchmark page is. A hand-maintained list
# of 450+ names drifts; `@autodocs Modules=[AIFloats]` has the opposite failure
# — it publishes private machinery (`get_table`, cache structs, `validformat`)
# into the user-facing reference while omitting public bindings that carry no
# docstring.
#
# The membership test is `Base.isexported` / `Base.ispublic`, so the page is
# exactly the public surface by construction, and the build FAILS if a public
# binding is undocumented (docs/refinedocs2.md P1-1, P1-2).

const REFERENCE_DIR = joinpath(@__DIR__, "src", "95-reference")

# Reviewed exemptions: public bindings deliberately absent from the reference.
# An entry here is a decision, not a convenience.
const REFERENCE_EXEMPT = [
    # Documented on `97-internals.md` instead, as explicitly unstable
    # implementation detail. Listing them here as well would be a duplicate
    # docstring, and would put a vendored carrier in the user-facing reference.
    :DyadicNumbers,
    :Dyadic,
]

# The generated format aliases. 120 of the 504 are exported (those with K <= 8),
# and each is one line saying it is the format its own name spells out —
# `Binary6p3ue` is `Binary(6, 3, UNSIGNED, EXTENDED)`. Listing them buried
# fourteen real entries under a hundred and twenty restatements of a naming
# scheme that `20-concepts.md` gives once and in full, and did the same to the
# page's index.
#
# They keep their docstrings and still answer to `?Binary6p3ue`. What they lose
# is a place in a listing they were drowning.
reference_exempt(n::Symbol) =
    n in REFERENCE_EXEMPT || occursin(r"^Binary\d+p\d+[su][fe]$", String(n))

# The reference is SPLIT across pages because the generated operation families
# are 154 substantial docstrings; one page of them renders past Documenter's
# size threshold and is unpleasant to load or search. Each entry is
#     (file slug, page title, [(section title, predicate), …])
# and predicates are tried in order across the whole tree — the FIRST match
# wins, so specific rules precede general ones and `nothing` means
# "everything still uncategorized".
const REFERENCE_PAGES = Any[
    ("10-core", "Formats, datums, projections", Any[
        ("Formats", n -> n in (:Binary, :IntParam, :CodeType, :ValueType, :codetype,
                               :valuetype, :Formats, :resolve_fields, :formatname,
                               :formatinfo)),
        ("Format axes", n -> n in (:ΣBool, :ΔBool, :SIGNED, :UNSIGNED, :FINITE, :EXTENDED,
                                   :is_signed, :is_unsigned, :is_finite, :is_extended)),
        ("Format queries", n -> endswith(String(n), "Of") ||
                                n in (:bitwidth, :signedness, :domain, :formatof,
                                      :codemask, :signmask, :orderkeytype, :codedistance)),
        ("Datums and the codec", n -> startswith(String(n), "Class") ||
                                      n in (:BinaryValue, :decode, :fromcode, :encode,
                                            :order_key, :nan_code, :posinf_code,
                                            :neginf_code, :codetable, :printcodetable,
                                            :Class, :FPClass, :NextGreaterThan,
                                            :NextLessThan, :CodeCountingSort)),
        ("Datum display", n -> n in (:VALID_SHOW_STYLES, :set_show_style!, :get_show_style)),
        ("Projections", n -> occursin(r"^(RT[EAPNZO]|RS[ABC])(_S[FPN])?$", String(n)) ||
                             String(n) in ("SF", "SP", "SN") ||
                             n in (:Projection, :RoundOf, :SatOf, :project,
                                   :project_interval, :round_to_precision, :saturate,
                                   :isstochastic, :nrandbits, :DefaultProjection,
                                   :DefaultRoundingMode, :DefaultSaturationMode,
                                   :with_projection)),
    ]),
    ("20-operations", "Operations, kernels, storage", Any[
        ("Scalar operations", n -> n in (:operations, :operationinfo) ||
                                   any(o -> o.name === n, AIFloats.operations())),
        ("Array kernels and tables", n -> n in (:vmap, :vmap!, :table_policy, :table_stats,
                                                :table_entries, :empty_tables!)),
        ("Packed storage", n -> startswith(String(n), "packed") ||
                                n in (:PackedVector, :packing_saves, :PACK_TILE)),
    ]),
    ("30-blocks", "Blocks and scaled operations", Any[
        ("Block containers", n -> n in (:Block, :BlockVector, :blocksize, :scaleformat,
                                        :elemformat, :blockdecode, :blockproject)),
        ("Block conversions", n -> startswith(String(n), "ConvertTo") ||
                                   startswith(String(n), "ConvertFrom")),
        ("Block operations", n -> startswith(String(n), "Block")),
        ("Scaled operations", n -> startswith(String(n), "Scaled")),
    ]),
    ("40-governance", "Conformance", Any[
        ("Conformance and \u03f0", n -> n in (:conformance, :conformance_dict,
                                         :conformance_report, :ConformanceDeclaration,
                                         :draft_revision, :draft_identity, :measure_kappa,
                                         :register_approx!, :unregister_approx!, :approx,
                                         :list_approx, :kappa, :kappa_measured,
                                         :ApproxImpl, :ftz_variant)),
        ("External formats", n -> n in (:binary16, :binary32, :binary64, :binary128,
                                        :bfloat16)),
        ("Types and formats", nothing),
    ]),
]

public_names() = sort!(filter(names(AIFloats; all = true)) do n
    Base.isexported(AIFloats, n) || Base.ispublic(AIFloats, n)
end)

reference_file(slug) = joinpath(REFERENCE_DIR, slug * ".md")
reference_relpath(slug) = "95-reference/" * slug * ".md"

function write_reference_pages()
    ns = filter(!reference_exempt, public_names())
    undocumented = filter(n -> !Docs.hasdoc(AIFloats, n), ns)
    isempty(undocumented) || error(
        "public bindings without documentation: " * join(undocumented, ", ") *
        "\ndocument them, or add a reviewed exemption to `reference_exempt` " *
        "(docs/refinedocs2.md P1-2)")

    mkpath(REFERENCE_DIR)
    remaining = copy(ns)
    total = 0
    for (slug, title, sections) in REFERENCE_PAGES
        io = IOBuffer()
        println(io, "# ", title, "\n")
        println(io, "```@meta\nCurrentModule = AIFloats\n```\n")
        println(io, "Part of the [Reference](@ref reference); see that page for how this ",
                    "listing is generated and what it guarantees.\n")
        println(io, "```@contents\nPages = [\"", slug, ".md\"]\nDepth = 2\n```")
        wrote = 0
        for (section, pred) in sections
            members = pred === nothing ? copy(remaining) : filter(pred, remaining)
            isempty(members) && continue
            setdiff!(remaining, members)
            wrote += length(members)
            println(io, "\n## ", section, "\n")
            println(io, "```@docs")
            foreach(n -> println(io, n), members)
            println(io, "```")
        end
        println(io, "\n## Index\n\n```@index\nPages = [\"", slug, ".md\"]\n```")
        write(reference_file(slug), String(take!(io)))
        total += wrote
    end
    isempty(remaining) || error("reference generator left names uncategorized: $remaining")

    # The landing page (95-reference.md) is hand-written and tracked; only the
    # sub-pages are generated. It must list every one of them, or a reader can
    # reach a section only through the sidebar.
    landing = read(joinpath(@__DIR__, "src", "95-reference.md"), String)
    for (slug, title, _) in REFERENCE_PAGES
        occursin(title, landing) || error(
            "docs/src/95-reference.md does not link the generated page \"$title\" ($slug)")
    end
    @info "reference pages generated" public = total pages = length(REFERENCE_PAGES)
    return nothing
end

# ---- the menu's section map -------------------------------------------------
# Documenter lists a page's own headings in the sidebar only for the page being
# read; for every other page the headings are simply not in the DOM. So a menu
# entry could show a marker for "there is more here" on exactly one page at a
# time, which is not a menu.
#
# search_index.js ships to every page and carries each heading's page, anchor and
# title — but not its LEVEL, so it cannot tell a `##` from a `###`, and a page's
# menu would list every subsubsection. The levels are in the built HTML, so the
# map is extracted from there and handed to assets/sidebar.js.
#
# That means a two-pass build: pass one produces the HTML, the map is read out of
# it, and pass two ships the map. The second pass runs only when the map actually
# changed, so an unchanged tree rebuilds once.

const MENU_SECTIONS_JS = joinpath(@__DIR__, "src", "assets", "menu-sections.js")

const H2_RE = r"<h2 id=\"([^\"]+)\"><a class=\"docs-heading-anchor\" href=\"#[^\"]*\">(.*?)</a>"s

_untag(s) = replace(s, r"<[^>]*>" => "")
_unescape(s) = foldl((a, p) -> replace(a, p), 
                     ["&amp;" => "&", "&lt;" => "<", "&gt;" => ">",
                      "&quot;" => "\"", "&#39;" => "'"]; init = s)
_jsstr(s) = "\"" * replace(s, "\\" => "\\\\", "\"" => "\\\"") * "\""

function collect_menu_sections()
    build = joinpath(@__DIR__, "build")
    isdir(build) || return Dict{String, Vector{Tuple{String, String}}}()
    out = Dict{String, Vector{Tuple{String, String}}}()
    for (root, _, files) in walkdir(build), f in files
        endswith(f, ".html") || continue
        rel = replace(relpath(joinpath(root, f), build), '\\' => '/')
        hs = Tuple{String, String}[]
        for m in eachmatch(H2_RE, read(joinpath(root, f), String))
            title = strip(_unescape(_untag(m.captures[2])))
            isempty(title) && continue
            # The id must be unescaped too: Documenter writes it into the
            # attribute as `Julia&#39;s-operators-…`, but the DOM — and so the
            # fragment a link has to name — holds `Julia's-operators-…`.
            push!(hs, (_unescape(m.captures[1]), title))
        end
        isempty(hs) || (out[rel] = hs)
    end
    out
end

function render_menu_sections(map)
    io = IOBuffer()
    println(io, "// GENERATED by docs/make.jl from the built HTML. Do not edit.")
    println(io, "//")
    println(io, "// Each page's level-2 headings, so assets/sidebar.js can offer every menu")
    println(io, "// entry the same expand/collapse as the groups. Regenerated on every docs")
    println(io, "// build; a stale copy costs a second build pass, never a wrong link.")
    println(io, "var documenterMenuSections = {")
    for page in sort!(collect(keys(map)))
        entries = join(("[$(_jsstr(a)), $(_jsstr(t))]" for (a, t) in map[page]), ", ")
        println(io, "  ", _jsstr(page), ": [", entries, "],")
    end
    println(io, "};")
    String(take!(io))
end

# The asset must exist before the first pass, even if empty.
isfile(MENU_SECTIONS_JS) || write(MENU_SECTIONS_JS, render_menu_sections(
    Dict{String, Vector{Tuple{String, String}}}()))

write_benchmark_page()
write_reference_pages()
check_page_tree()

build_docs() = makedocs(;
    modules = [AIFloats],
    authors = "Jeffrey Sarnoff <jeffrey.sarnoff@ieee.org>",
    # A Remotes.GitHub, not a format string: with a string, Documenter cannot
    # derive the repository root for the navbar link and warns on every build.
    repo = Remotes.GitHub("JeffreySarnoff", "AIFloats.jl"),
    sitename = "AIFloats.jl",
    format = Documenter.HTML(;
        canonical = "https://JeffreySarnoff.github.io/AIFloats.jl",
        # Sidebar menu behaviour Documenter's CSS cannot express on its own:
        # a collapse that cascades, and an accordion on the active page's own
        # section list. See the files.
        assets = ["assets/sidebar.css", "assets/content.css",
                  "assets/menu-sections.js", "assets/sidebar.js"],
        # Direct `.html` targets work both on the deployed site and when a
        # generated build is opened from disk. Pretty directory URLs require
        # an HTTP server to resolve `path/` to `path/index.html`; without one,
        # a click exposes the directory and makes the reader select index.html.
        # README links must match this choice — they name `.html` files.
        prettyurls = false,
        # Collapse the sidebar's top-level entries. At Documenter's default of 2
        # only a page's own headings collapse, so the multi-page groups
        # (Examples, Reference) list every child page at all times while a
        # single-page entry like Algorithms shows its sections only when active
        # — two behaviours in one menu. At 1 the groups behave like the pages:
        # closed until the reader opens them.
        collapselevel = 1,
        # 95-reference.md is one page holding every public docstring in the
        # package, several of which carry the measurement tables that justify a
        # policy constant. It exceeds Documenter's 200 KiB default on its own.
        size_threshold = 500 * 1024,
        size_threshold_warn = 400 * 1024,
    ),
    pages = PAGES,
    # Not `:all`. The reference page is generated from `Base.isexported` /
    # `Base.ispublic`, so every PUBLIC binding is in the manual by construction
    # and the generator errors if one is not. Private docstrings — cache keys,
    # policy constants, carrier probes — are deliberately absent from the user
    # reference (docs/refinedocs2.md P1-1); `:all` would demand they be added.
    checkdocs = :public,
)

build_docs()

# Pass two, only if the map moved. `menu-sections.js` is an input to the build
# and an output of it, so the first build after a page's headings change ships
# the previous map; rebuilding with the new one settles it. An unchanged tree
# takes this branch never.
# Documenter checks `@ref` links, and lychee checks that pages exist — neither
# checks that a FRAGMENT resolves. A link into `page.html#anchor` whose anchor was
# renamed still renders, still points at a real page, and still lands the reader
# nowhere near what it named. Every internal `page.html#fragment` in the built
# site is verified here, which also holds any hand-written link inside a
# `@raw html` block to the same standard as an `@ref`.
function check_fragments()
    build = joinpath(@__DIR__, "build")
    ids = Dict{String, Set{String}}()
    pages = String[]
    for (root, _, files) in walkdir(build), f in files
        endswith(f, ".html") || continue
        rel = replace(relpath(joinpath(root, f), build), '\\' => '/')
        push!(pages, rel)
        html = read(joinpath(root, f), String)
        ids[rel] = Set(m.captures[1] for m in eachmatch(r"\sid=\"([^\"]+)\"", html))
    end
    bad = String[]
    for page in pages
        dir = dirname(page)
        html = read(joinpath(build, page), String)
        for m in eachmatch(r"href=\"([^\":#]+\.html)#([^\"]+)\"", html)
            target = normpath(joinpath(dir, m.captures[1]))
            target = replace(target, '\\' => '/')
            haskey(ids, target) || (push!(bad, "$page -> $(m.captures[1]) (no such page)"); continue)
            frag = replace(m.captures[2], "&amp;" => "&", "&#39;" => "'", "&quot;" => "\"")
            frag in ids[target] ||
                push!(bad, "$page -> $(m.captures[1])#$(frag) (no such anchor)")
        end
    end
    isempty(bad) || error("dangling internal fragment link(s):\n  " * join(unique(bad), "\n  "))
    @info "internal fragment links check out" pages = length(pages)
    return nothing
end

check_fragments()

let fresh = render_menu_sections(collect_menu_sections())
    if fresh != read(MENU_SECTIONS_JS, String)
        @info "menu section map changed; rebuilding so the sidebar ships it"
        write(MENU_SECTIONS_JS, fresh)
        build_docs()
    end
end

deploydocs(; repo = "github.com/JeffreySarnoff/AIFloats.jl")
