using AIFloats
using Documenter

DocMeta.setdocmeta!(AIFloats, :DocTestSetup, :(using AIFloats); recursive = true)

# Add titles of sections and overrides page titles
const titles = Dict(
    # "10-tutorials" => "Tutorials", # example folder title
    "91-developer.md" => "Developer docs",
)

function recursively_list_pages(folder; path_prefix="")
    pages_list = Any[]
    for file in readdir(folder)
        if file == "index.md"
            # We add index.md separately to make sure it is the first in the list
            continue
        end
        # this is the relative path according to our prefix, not @__DIR__, i.e., relative to `src`
        relpath = joinpath(path_prefix, file)
        # full path of the file
        fullpath = joinpath(folder, relpath)

        if isdir(fullpath)
            # If this is a folder, enter the recursion case
            subsection = recursively_list_pages(fullpath; path_prefix=relpath)

            # Ignore empty folders
            if length(subsection) > 0
                title = if haskey(titles, relpath)
                titles[relpath]
                else
                @error "Bad usage: '$relpath' does not have a title set. Fix in 'docs/make.jl'"
                relpath
                end
                push!(pages_list, title => subsection)
            end

            continue
        end

        if splitext(file)[2] != ".md" # non .md files are ignored
            continue
        elseif haskey(titles, relpath) # case 'title => path'
            push!(pages_list, titles[relpath] => relpath)
        else # case 'title'
            push!(pages_list, relpath)
        end
    end

    return pages_list
end

function list_pages()
    root_dir = joinpath(@__DIR__, "src")
    pages_list = recursively_list_pages(root_dir)

    return ["index.md"; pages_list]
end

# ---- benchmark page ---------------------------------------------------------
# The results page is GENERATED at docs-build time by running the suite in its
# own project, as a subprocess. A subprocess and not an `include` because
# Chairmarks belongs to benchmark/Project.toml and must not become a dependency
# of the docs (or of the package) — the same isolation the suite itself keeps.
#
# Set AIFLOATS_DOCS_BENCHMARKS=0 to skip the run; the page is still written, and
# says plainly that it holds no measurements. A failed or skipped run must never
# fail the docs build: the numbers are informative, the prose around them is the
# documentation.

const BENCH_PAGE = joinpath(@__DIR__, "src", "60-benchmarks.md")

function run_benchmarks()
    root = dirname(@__DIR__)
    proj = joinpath(root, "benchmark")
    script = joinpath(proj, "runbenchmarks.jl")
    # Fixed at 4 unless overridden, not `auto`: the threading rows exist to be
    # compared against each other and against THREAD_MIN_ELEMS, which was refit
    # at four threads. A machine-dependent thread count would make two builds
    # incomparable for the one thing those rows are for.
    nthreads = get(ENV, "JULIA_NUM_THREADS", "4")
    run(`$(Base.julia_cmd()) --project=$proj --startup-file=no -e
         "import Pkg; Pkg.instantiate()"`)
    read(`$(Base.julia_cmd()) --project=$proj --startup-file=no -t $nthreads $script`, String)
end

function write_benchmark_page()
    header = """
    # [Benchmark results](@id benchmarks)

    Generated by running `benchmark/runbenchmarks.jl` during this documentation
    build. Nothing here is hand-entered.

    **These numbers describe the machine that built this page**, recorded in the
    header below along with the commit and the thread count. A shared CI runner
    is noisy and its absolute times mean little; the *ratios* between rows on one
    run are the informative part. Reproduce locally with:

    ```
    julia --project=benchmark -t 4 benchmark/runbenchmarks.jl          # all suites
    julia --project=benchmark -t 4 benchmark/runbenchmarks.jl scalar   # one suite
    ```

    The suite is run with four threads unless `JULIA_NUM_THREADS` says
    otherwise, whatever the machine's core count, so that the threading rows
    stay comparable between builds.

    What the columns mean: time per call, then allocations and bytes when a call
    allocates at all (their absence is itself the claim — most scalar rows are
    allocation-free), and elements per second for array rows. The `latency`
    suite measures package load and first-call compilation in *fresh processes*,
    because those happen exactly once and cannot be sampled.

    See [Performance characteristics](@ref performance) for the design decisions
    these measurements justify.

    """
    body = if get(ENV, "AIFLOATS_DOCS_BENCHMARKS", "1") in ("0", "false", "no")
        "!!! note \"Not run\"\n    " *
        "This build set `AIFLOATS_DOCS_BENCHMARKS=0`, so no benchmarks were run.\n"
    else
        try
            "```\n" * run_benchmarks() * "```\n"
        catch err
            @warn "benchmark suite did not run; the page will say so" exception = err
            "!!! warning \"Benchmarks did not run\"\n    " *
            "The suite failed to run during this build. See `benchmark/` to run it " *
            "locally.\n"
        end
    end
    write(BENCH_PAGE, header * body)
end

write_benchmark_page()

makedocs(;
    modules = [AIFloats],
    authors = "Jeffrey Sarnoff <jeffrey.sarnoff@ieee.org>",
    repo = "https://github.com/JeffreySarnoff/AIFloats.jl/blob/{commit}{path}#{line}",
    sitename = "AIFloats.jl",
    format = Documenter.HTML(;
        canonical = "https://JeffreySarnoff.github.io/AIFloats.jl",
        # 95-reference.md is one page holding every docstring in the package,
        # several of which carry the measurement tables that justify a policy
        # constant. It exceeds Documenter's 200 KiB default on its own.
        size_threshold = 500 * 1024,
        size_threshold_warn = 400 * 1024,
    ),
    pages = list_pages(),
)

deploydocs(; repo = "github.com/JeffreySarnoff/AIFloats.jl")
