using JSON: JSON
using SHA: sha256
using JuliaFormatter: format_text

const ROOT = normpath(joinpath(@__DIR__, ".."))
const SOURCE = joinpath(ROOT, "inventory", "operations.json")
tuple_code(xs) = "(" * join(xs, ", ") * (length(xs)==1 ? "," : "") * ")"
snake(s) = lowercase(
    replace(replace(s, r"([A-Z]+)([A-Z][a-z])"=>s"\1_\2"), r"([a-z0-9])([A-Z])"=>s"\1_\2"),
)

function generated_outputs()
    operations = JSON.parsefile(SOURCE)["operations"]
    header = "# Generated by tools/generate.jl; do not edit.\n# Input SHA256: $(bytes2hex(sha256(read(SOURCE))))\n"
    wrappers, kernels, tables = IOBuffer(), IOBuffer(), IOBuffer()
    print(wrappers, header)
    print(kernels, header)
    print(tables, header)
    known = Dict(
        "Convert"=>"identity",
        "Abs"=>"magnitude",
        "Negate"=>"negate",
        "CopySign"=>"copy_sign",
        "Add"=>"add",
        "Subtract"=>"subtract",
        "Multiply"=>"multiply",
        "Divide"=>"divide",
        "FMA"=>"fused_multiply_add",
        "FAA"=>"fused_add_add",
        "Recip"=>"reciprocal",
        "Clamp"=>"clamp_value",
        "Hypot"=>"hypot_value",
        "ArcTan2"=>"atan2_value",
    )
    numeric, plain, block =
        Tuple{String,Int}[], Tuple{String,Int}[], [("ConvertFromBlock", 3), ("ConvertToBlock", 3)]
    kernel_names = Pair{String,String}[]
    for o in operations
        name, n = String(o["name"]), Int(o["arity"])
        if !o["wrapper"]
            if name in ("RoundOf", "SatOf") || !(
                startswith(name, "Block") ||
                startswith(name, "ConvertToBlock") ||
                name=="ConvertFromBlock"
            )
                push!(plain, (name, count(p->startswith(p, "f"), o["parameters"])))
            end
            continue
        end
        k = get(known, name, snake(name)*"_value")
        push!(kernel_names, name=>k)
        if !haskey(known, name)
            if startswith(name, "Minimum") || startswith(name, "Maximum")
                println(
                    kernels,
                    "$k(x, y) = extrema(x, y; maximum=$(startswith(name,"Maximum")), number=$(endswith(name,"Number")), finite_only=$(endswith(name,"Finite")), by_magnitude=$(occursin("Magnitude",name)))",
                )
            elseif name=="ArcTan2Pi"
                println(kernels, "$k(y, x) = divide(atan2_value(y, x), PI)")
            else
                println(kernels, "$k(x) = elementary(:$name, x)")
            end
        end
        args = String.(vcat(o["parameters"], o["operands"]))
        fs = String.(o["parameters"][1:n])
        cs = String.(o["operands"])
        println(
            wrappers,
            "\"\"\"$name($(join(args,", "))): source §$(o["clause"]); exact kernel and final projection.\"\"\"",
        )
        println(
            wrappers,
            "$name($(join(args,", "))) = P.scalar(P.$k, $(tuple_code(fs)), fr, rho, $(tuple_code(cs)))",
        )
        println(wrappers, "public $name")
        push!(numeric, (name, n+1))
        sf = [x for i = 1:n for x in ("fs$i", "f$i")]
        sc = [x for i = 1:n for x in ("s$i", "c$i")]
        bc = [x for i = 1:n for x in ("s$i", "cs$i")]
        pairs = tuple_code(["(fs$i, f$i)" for i = 1:n])
        println(
            wrappers,
            "\"\"\"Scaled$name: singleton block semantics with one final projection.\"\"\"",
        )
        println(
            wrappers,
            "Scaled$name($(join(vcat(sf,["fr","rho"],sc),", "))) = P.scaled(P.$k, $pairs, fr, rho, $(tuple_code(["(s$i, c$i)" for i in 1:n])))",
        )
        println(
            wrappers,
            "\"\"\"Block$name: positional elementwise semantics, retaining result scale s.\"\"\"",
        )
        println(
            wrappers,
            "Block$name($(join(vcat(["n"],sf,["fs","fr","rho"],bc,["s"]),", "))) = P.block_apply(P.$k, n, $pairs, fs, fr, rho, $(tuple_code(["(s$i, cs$i)" for i in 1:n])), s)",
        )
        println(wrappers, "public Scaled$name, Block$name\n")
        push!(numeric, ("Scaled"*name, 2n+1))
        push!(block, ("Block"*name, 2n+2))
    end
    for (name, rows) in
        (("NUMERIC_ARITIES", numeric), ("PLAIN_ARITIES", plain), ("BLOCK_ARITIES", block))
        println(tables, "const $name = (")
        for (n, a) in sort(rows; by = x->(x[2], x[1]))
            println(tables, "    (", repr(n), ", ", a, "),")
        end
        println(tables, ")")
    end
    println(kernels, "const OPERATION_KERNELS = (")
    for (name, k) in kernel_names
        println(kernels, "    $name = $k,")
    end
    println(kernels, ")")
    return Dict(
        file=>format_text(body; indent = 4, margin = 100) for (file, body) in (
            "generated_operations.jl"=>String(take!(wrappers)),
            "generated_kernels.jl"=>String(take!(kernels)),
            "arity_tables.jl"=>String(take!(tables)),
        )
    )
end
function main(args)
    args in (String[], ["--check"]) || error("usage: generate.jl [--check]")
    for (file, body) in generated_outputs()
        path = joinpath(ROOT, "src", file)
        if "--check" in args
            isfile(path) && read(path, String)==body || error("generated output differs: $file")
        else
            write(path, body)
        end
    end
    println("PASS deterministic wrapper, kernel-adapter and arity generation")
end
if abspath(PROGRAM_FILE) == @__FILE__
    main(ARGS)
end
